### ISSUE TITLE
Recurring notification/alert

### ISSUE THREAD

**Issue by matthieupinte** [Agontuk/react-native-geolocation-service#10]
Hi,

First, thanks for your work... you saved my app ^^ !

I'm just here to see if you got a solution, some of my users are answering "Cancel" when this popup/notif/alert appears... (sorry, screen in french)

![screenshot_20180227-173032](https://user-images.githubusercontent.com/2217014/36741428-5f94ba66-1be5-11e8-879e-626bea01fc5a.png)

It means :
> "To obtain best results, allow your device to activate localization, that use Google service localization" "Cancel" "Ok"

If they press "Cancel", the popup reappear instantly, again, and again, and again ... 

Hope someone will find a solution. Some of them do not want to enable localization...

**Comment by Agontuk** [comment]
If user cancel, you'll get an error object in the error callback with code 5. If the alert is appearing again, it means you're probably requesting location again on error callback. Check your code.

**Comment by matthieupinte** [comment]
Yes, you're right, my bad...

**Comment by matthieupinte** [comment]
You're right, I'm asking 2-3 times `getCurrentPosition`... this is not good.
I didn't see that before, because, when `navigator.geolocation.getCurrentPosition` failed in RN (because no permission granted), no "notifications"/alert are shown.
With your package, here, you're always asking user if he is agree by using `Google's location service` (cause it will change it's settings directly)...

I need to find a way to don't ask again by your package `getCurrentPosition` if it's because of `SETTINGS_NOT_SATISFIED`... by a boolean... but also need to find if he changed is settings directly.

**Comment by zsajjad** [comment]
Can we make this prompt optional? I have a scenario where I want device's location only when location service is enabled else app will proceed without location data. With current flow, app waits at the very beginning unless user responds to this dialog.

**Comment by Agontuk** [comment]
It's possible, I'll take a look. Maybe we can expose another option to disable the dialog like this -
```js
Geolocation.getCurrentPosition(
    (success) => {},
    (error) => {},
    { enableHighAccuracy: true, showLocationDialog: false }
);
```

**Comment by Agontuk** [comment]
New version is released with the option to disable location dialog.
