### ISSUE TITLE
TypeError: Cannot read property 'getCurrentPosition' of undefined ( rn 0.60.3)

### ISSUE THREAD

**Issue by Return-1** [Agontuk/react-native-geolocation-service#100]
When using
`import Geolocation from '@react-native-community/geolocation';`
things work as expected. However when using
`import Geolocation from 'react-native-geolocation-service';`

it yields: 

> TypeError: Cannot read property 'getCurrentPosition' of undefined

platform: iOS
rn_version: 0.60.3
react-native-geolocation-service:  2.0.1

**Comment by Return-1** [comment]
any updates on this one?

**Comment by herlarb** [comment]
@Return-1  try pulling version 3.0.0 from npm and see if it fixes your issue

**Comment by Return-1** [comment]
did earlier in the day and forgot to come back here, yes 3.0.0 solves the issue

**Comment by herlarb** [comment]
@Return-1  kindly close the issue. Thanks glad you were able to resolve your issue
