### ISSUE TITLE
Error: cannot find symbol class ActivityCompat

### ISSUE THREAD

**Issue by jcamilo97** [Agontuk/react-native-geolocation-service#101]
platform: Android
RNversion: 0.59.10
react-native-geolocation-service: 2.0.1

> build.gradle dependencies

![image](https://user-images.githubusercontent.com/19734429/61448977-932d3200-a919-11e9-8f2b-372c93f73fa4.png)

> Error

![image](https://user-images.githubusercontent.com/19734429/61448771-26199c80-a919-11e9-8c07-0f16dc984a42.png)

**Comment by arahmanali** [comment]
any update?

**Comment by AtharZaib** [comment]
same error ..

**Comment by snamstorm** [comment]
Also getting this error

**Comment by Kamill90** [comment]
the same. It is the first library I need to integrate and I do it on a fresh react-native starter app. It works perfectly fine on iOS but cannot find any workaround for android. Any suggestion?

**Comment by Agontuk** [comment]
I've a fix for this in `rn60` branch. WIll merge it in master and do a new release as soon as possible.

**Comment by Kamill90** [comment]
Merge it!

**Comment by Agontuk** [comment]
New version is available, so closing this issue.

On another note, if you're using RN 0.59 or below, don't use `play-services-location` greater than 16.0.0 because the later versions have breaking changes.

**Comment by jaburcodes** [comment]
still facing it

**Comment by lutakyn** [comment]
I'm also facing the same issue,I'm using  version 3.0.0

**Comment by santiagofm** [comment]
@Agontuk That fix doesn't seem to be merged to master yet. Can you take a look?

**Comment by pierroo** [comment]
@Agontuk I am also facing this issue, using RN 0.60;

can you please let us know if it was actually merged to master?

Thank you for your time!

**Comment by jmhinric** [comment]
@Agontuk could you please merge this commit of yours on branch `rn60-fix`? Is there any reason not to do so?

https://github.com/Agontuk/react-native-geolocation-service/commit/748bd6721e26b4400139f2973d477326eee382bd

**Comment by Agontuk** [comment]
@jmhinric , are you using play-services-location version greater than 16.0.0 ? Currently master branch is working fine even without this fix.

**Comment by jmhinric** [comment]
@Agontuk I got it working- like the previous comment, it was the npx jetify.  Thanks!

**Comment by gluons** [comment]
`npx jetify` workaround works like a charm.  
Wish RN 0.60 fix will land soon. Thank you.
