### ISSUE TITLE
React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by AilsonFreire** [Agontuk/react-native-geolocation-service#103]
When I try to build the app on ios devices, after manually link the libary to IOS as the read.me shows, I got this error: 

node_modules/@react-native-community/geolocation/ios/RNCGeolocation.h:8:9: fatal error: 'React/RCTEventEmitter.h' file not found
#import <React/RCTEventEmitter.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~

RNative: 60.4
react-native-geolocation-service: 3.0.0

**Comment by oakis** [comment]
Did you try linking it automatically?

**Comment by EugenePizzerbert** [comment]
Same error
![image](https://user-images.githubusercontent.com/40814780/61805582-a172d500-ae68-11e9-86c4-c7b2e0f6151e.png)

RNative: 60.4
react-native-geolocation-service: 3.0.0

**Comment by AilsonFreire** [comment]
@EugenePizzerbert Try to install @react-native-community/geolocation, linking and then use pod install, e tell with this works.

**Comment by EugenePizzerbert** [comment]
@AilsonFreire

**Comment by EugenePizzerbert** [comment]
@AilsonFreire 
I got same error.
Can you share how to do step by step?
Can you show me pod file for this?

**Comment by AilsonFreire** [comment]
Sorry @EugenePizzerbert, I didn't remember how I handle this issue. Here is what my docs says: I installed the library as a said above, and linking using "react-native link @react-native-community/geolocation", then used pod install. Installed this library react-native-geolocation-service, linking, and again pod install, I didn't follow the "install manually ios" from this library. Finally, I cleaned the project for both android and IOS and buit again and it worked.

**Comment by funnyjerry** [comment]
**Thanks** a lot @AilsonFreire
Solved issue 
🤗🤗🤗🤗🤗🤗🤗

**Comment by oakis** [comment]
> **Thanks** a lot @AilsonFreire
> Solved issue
> 🤗🤗🤗🤗🤗🤗🤗

Could you close the issue? For future reference it is good to have a clean-script which you run before all build commands. 

package.json:
```
"clean": "cd android && ./gradlew clean"
```

**Comment by GabeConsalter** [comment]
> @EugenePizzerbert Try to install @react-native-community/geolocation, linking and then use pod install, and this works.

Works like a charm.

**Comment by Agontuk** [comment]
I've updated the README for 0.60, please follow the instruction and it should work fine.
