### ISSUE TITLE
Cannot get correct updated location data

### ISSUE THREAD

**Issue by nakiscia** [Agontuk/react-native-geolocation-service#107]
Hello, 

In the android version of our app, geolocation service return same value again and again. However, if I open Google Maps and return the application it returns different/updated location data.
I tried to change watch position, high accuracy option, maxAge option and none of them gives the correct result. 

Can you give me a suggestion to fix this problem?

**Comment by jmoliugp** [comment]
I'm experiencing the same issue as @nakiscia on the iOS simulator. It started fetching the correct coordinates using the workaround he mentioned.

I'm using the `2.0.0` version.

**Comment by Agontuk** [comment]
You'll always get same location in emulator/simulator because it is fake. Use real device to test location update.

**Comment by fang5502** [comment]
I also have the same problem with the android emulator, but I set the option forceRequestLocation to true to solve the problem.

**Comment by aruhn1** [comment]
I believe the issue mentioned by the OP @nakiscia is on a real device, not simulator. I have the same issue (on a real device, connected in debug mode). I'll check in more detail and update.
