### ISSUE TITLE
Can I get the location provider?

### ISSUE THREAD

**Issue by jpmdl** [Agontuk/react-native-geolocation-service#114]
Hey there,

Great work!

Sorry if this is not the appropriate channel for this, but can I get the provider of the location provided (3G, Wifi or GPS)?

Thanks!

**Comment by jameshowe** [comment]
Wrong library, see [@react-native-community/netinfo](https://github.com/react-native-community/react-native-netinfo#netinfocellulargeneration).

**Comment by jpmdl** [comment]
Thanks, I can have the wrong library, but NetInfo is not what I’m looking for.

I’m trying to get the Location Provider for each of my LatLng coordinates and not what type of connection I’m using to the web. 

The info can be seen here for Android:
https://developer.android.com/reference/kotlin/android/location/LocationManager#GPS_PROVIDER:kotlin.String

**Comment by Agontuk** [comment]
Sorry for the late reply, google play service does not guarantee which provider it'll use to fetch location. It'll find the suitable provider based on the configuration.
