### ISSUE TITLE
@react-native-community

### ISSUE THREAD

**Issue by cipriancaba** [Agontuk/react-native-geolocation-service#115]
Why is this package not replacing the react-native-community one? https://github.com/react-native-community/react-native-geolocation

**Comment by oakis** [comment]
```js
"dependencies": {
    "@react-native-community/geolocation": "^1.4.2"
},
```

Do you want to elaborate?

**Comment by cipriancaba** [comment]
Well, it is really confusing to have 3 options to use the geolocation package.. one is in react native core up to version 0.60, one is react-native-geolocation and the other is react-native-geolocation-service..

Also there is this weird warning on the react-native-community package that states
```
Currently, on Android, this uses the android.location API. This API is not recommended by Google because it is less accurate and slower than the recommended Google Location Services API. This is something that we want to change in the near future https://github.com/react-native-community/react-native-geolocation/issues/6.
```

I've spent a lot of time debugging Android and trying to make it work until i finally installed this package that works beautifully.

So my question is, why doesn't this package with the Google Location Services API replace the react-native-community version?

**Comment by oakis** [comment]
Its like with everything, there are multiple solutions to the same problem.

This package is also mentioned here:
https://facebook.github.io/react-native/docs/geolocation
