### ISSUE TITLE
Location Fluctuations in watchPostition

### ISSUE THREAD

**Issue by sarthak216-blr** [Agontuk/react-native-geolocation-service#116]
## Environment
react-native-cli: 2.0.1
react: 16.6.3
react-native: 0.59.8 

## Platforms
Android & iOS both

## Versions
- Android:
- iOS:
- react-native-geolocation-service: 3.0.0,
- react-native:16.6.3
- react:0.59.8

## Description
My Latitude and longitude keeps on fluctuating, even i am still with the device. Sometimes the spikes are small and some times it's large. Here is code :-

this.watchId = Geolocation.watchPosition(
            (position) => {
              console.log("Position Received",position);
              let LocationData = position.coords;
                this.setState({
                    region: {
                        latitude: LocationData.latitude,
                        longitude: LocationData.longitude,
                        longitudeDelta:LONGITUDE_DELTA,
                        latitudeDelta:LATITUDE_DELTA,
                    },
                  })  
                
            },
            (error) => {
              console.log(error);
            },
            { enableHighAccuracy: true, distanceFilter: 0, interval: 100, fastestInterval: 2000 }
          );

**Comment by sarthak216-blr** [comment]
Any updates on this ??

**Comment by jyothiMenda** [comment]
Any update on this?

**Comment by Agontuk** [comment]
Sorry for the late reply, you can use distanceFilter option to reduce location bounces. Also, why are your interval is set to lower than fastestInterval ?
