### ISSUE TITLE
RNFusedLocation is undefined

### ISSUE THREAD

**Issue by giovanischiar** [Agontuk/react-native-geolocation-service#117]
Hello,

I'm using RN 60 and added this library following the instructions, but when I run the app I got this strange error on Android. What it could be?

Versions:
react-native: 0.60.5
react-native-geolocation-service: ^3.1.0

For more versions of stuff just contact.

**Comment by jothikannan** [comment]
I am also getting the same error.

**Comment by Agontuk** [comment]
Did you change any files inside android folder ? There's no setup needed for RN0.60+ versions, just installing the package should work.

**Comment by jramalho** [comment]
Here too. Any changes in the package itself... just using the Doc too.

**Comment by baatar777** [comment]
I am also having the same issue...

**Comment by Agontuk** [comment]
Pretty sure it's setup related issue. Try the manual setup if auto linking does not work. Closing this for now, feel free to open new issue.
