### ISSUE TITLE
iOS: Handle network connection in error callback

### ISSUE THREAD

**Issue by latusdenis** [Agontuk/react-native-geolocation-service#118]
Does the library handle network error, while finding the location?

I am switching off the Internet, while searching the geolocation and the error callback isn't invoked only on iOS.

My config:
```
GeolocationService.getCurrentPosition(
      (geoPosition: GeoPosition) => {
        console.log(geoPosition);
      },
      error => {
        setIsLoading(false);
    },
      { enableHighAccuracy: true, timeout: 1000, maximumAge: 10000 }
    );
```

**Comment by Agontuk** [comment]
Sorry for the late reply, if the problem still persists please file an issue here [https://github.com/react-native-community/react-native-geolocation/issues](https://github.com/react-native-community/react-native-geolocation/issues)
