### ISSUE TITLE
Background location update is possible in IOS?

### ISSUE THREAD

**Issue by ramkiakil** [Agontuk/react-native-geolocation-service#119]

**Comment by muhammedjailam** [comment]
on IOS even when u add NSLocationAlwaysUsageDescription, the privacy settings location page does not show 'Always' option in iOS 13. Why ? and how to enable it ?

**Comment by muhammedjailam** [comment]
This Helped
https://github.com/Agontuk/react-native-geolocation-service/issues/67

**Comment by ramkey-akil** [comment]
Thanks @muhammedjailam

**Comment by Agontuk** [comment]
This module uses the `react-native-community/geolocation` package for iOS module. So it'll be better to create a issue there regarding this.
