### ISSUE TITLE
Merge with react-native

### ISSUE THREAD

**Issue by brunolemos** [Agontuk/react-native-geolocation-service#12]
Maybe this should be in react-native official package?

**Comment by Agontuk** [comment]
That wouldn't be viable, because it'll introduce google play service dependency in RN framework. Also even if someone doesn't use geolocation in their apps, it'll still get compiled when building the app.

But if they decide to merge it (highly unlikely), I'll gladly help.

**Comment by brunolemos** [comment]
Ok. There isn't any PR there for discussion?
