### ISSUE TITLE
README is misleading

### ISSUE THREAD

**Issue by GunnarAK** [Agontuk/react-native-geolocation-service#122]
The Readme states you have to install this library by doing:
`npm install react-native-geolocation-service --save`
This is all good and all, but when viewing the iOS specific setup for 0.59 one has to install the community version ??

https://github.com/Agontuk/react-native-geolocation-service#setup

Android does not talk about the community version but `react-native-geolocation-service`
The iOS setup seems wrong

**Comment by draperunner** [comment]
`@react-native-community/geolocation` is a dependency of this package (`react-native-geolocation-service`). You don't need to install `@react-native-community/geolocation` explicitly. 

I wouldn't say the README is misleading as it never says that you need to install the community package, but I can understand that it can seem strange to import a podspec from another package.

**Comment by iRyusa** [comment]
Just did an upgrade from 0.59 -> 0.60 and current version doesn't install the RNGeolocation when doing a `pod install`. Adding `@react-native-community/geolocation` did the trick tho.

**Comment by Agontuk** [comment]
You don't need to install `@react-native-community/geolocation` separately as it'll be installed along with this library. You just need to add it to the Podfile and run `pod install`.

I'll update the doc to clarify that it uses `@react-native-community/geolocation` under the hood for iOS module.
