### ISSUE TITLE
GeoPosition TypeScript definition incomplete

### ISSUE THREAD

**Issue by Sakarisson** [Agontuk/react-native-geolocation-service#124]
On Android, the `GeoPosition` object has a `mocked` member, which will either be `true` or `false`. iOS location objects to not have this key. This is not represented in the type definition:

```typescript
  export interface GeoPosition {
    coords: GeoCoordinates
    timestamp: number
  }
```

I suggest adding an optional `mocked` filed to the `GeoPosition` type. I can create the PR myself as soon as I get a confirmation from the library's maintainers.

**Comment by Sakarisson** [comment]
Since this is such a simple request, I just made the PR right away.

**Comment by Agontuk** [comment]
PR merged, so closing this.
