### ISSUE TITLE
watchposition location update not updating continuously in ios

### ISSUE THREAD

**Issue by ramkey-akil** [Agontuk/react-native-geolocation-service#128]
Geolocation.watchPosition((position)=>{
 },(error) => console.log(JSON.stringify(error)),
  {enableHighAccuracy: true,distanceFilter:10,interval:1000,useSignificantChanges:true})

**Comment by Agontuk** [comment]
Set `useSignificantChanges: false` and try again. Otherwise create an issue in [https://github.com/react-native-community/react-native-geolocation/issues](https://github.com/react-native-community/react-native-geolocation/issues)
