### ISSUE TITLE
Accuracy unit in getCurrentPosition()

### ISSUE THREAD

**Issue by King2231** [Agontuk/react-native-geolocation-service#133]
I am using the getCurrentPosition() method of the library. I wish to show accuracy of the location in my app. The method returns accuracy but i am unsure the unit of the accuracy. Is it some kind of a percentage or meters(like whatsapp). Kindly help.

**Comment by oakis** [comment]
It's in meters.

https://stackoverflow.com/a/7812357/5458928

> The accuracy attribute denotes the accuracy level of the latitude and longitude coordinates. It is specified in **meters** and must be supported by all implementations. The value of the accuracy attribute must be a non-negative real number.
