### ISSUE TITLE
watchPosition returning two successive callbacks when created in ios

### ISSUE THREAD

**Issue by vinithreddy3** [Agontuk/react-native-geolocation-service#139]
Device                   : iphone X
Device Version      : 11.4.1
Package Version   : 2.0.1
options used        : { distanceFilter : 25 , enableHighAccuracy : true }
Issue  :  watchPosition returns 2-3 success callbacks with same location coordinates whenever created where there is expected to be only 1 success callback

**Comment by Agontuk** [comment]
Sorry for the late reply, if the problem still persists try updating to the latest version. If it still does not work, file an issue in [https://github.com/react-native-community/react-native-geolocation/issues](https://github.com/react-native-community/react-native-geolocation/issues)
