### ISSUE TITLE
Permission not requested when both NSLocationAlwaysUsageDescription and NSLocationWhenInUseUsageDescription on plist

### ISSUE THREAD

**Issue by Return-1** [Agontuk/react-native-geolocation-service#143]
When invoking `getCurrentPosition` , the permission dialogue is not invoked when both **NSLocationAlwaysUsageDescription** and **NSLocationWhenInUseUsageDescription** are on the plist.

The problem here is that they both need to be on the .plist because of the very common `react-native-permissions` library.

This can lead to a scenario like i'm facing where i'm forced to use one of the two. Anyone else facing that or any advice on the subject?

------

version: any
Device: iphone 6
Ios: 12.3.1

**Comment by sercanov** [comment]
Yeah, I also had this issue. You'll need to set `authorizationLevel` explicitly

```javascript
    Geolocation.setRNConfiguration({
      authorizationLevel: 'whenInUse',
      skipPermissionRequests: false,
    });
```

**Comment by Return-1** [comment]
> Yeah, I also had this issue. You'll need to set `authorizationLevel` explicitly
> 
> ```js
>     Geolocation.setRNConfiguration({
>       authorizationLevel: 'whenInUse',
>       skipPermissionRequests: false,
>     });
> ```

Thank you. Additionally it appears that `react-native-permissions` v2.x.x now supports individual permissions too so there are more than one solutions to this issue
