### ISSUE TITLE
Location won't update after interval timeout

### ISSUE THREAD

**Issue by TailNest** [Agontuk/react-native-geolocation-service#145]
Hello there, I'm using this module to update the location of the device every 10 seconds. This is the code:

```
    this.setState({
      watchPos: Geolocation.watchPosition(
        (position) => {
          this.props.dispatch({type: "SET_STATUS", payload: "Setting position...\n"})
          this.props.dispatch({
            type: "SET_DEVICE_POSITION",
            payload: position.coords,
          })
          this.props.dispatch({type: "SET_STATUS", payload: `lat: ${position.coords.latitude}, long: ${position.coords.longitude}\n`})
          if (this.state.selectedLocation) {
            this.sendLocationToDevice()
          }

          this.props.dispatch({type: "STOP_LOADER"})
        },
        (error) => {
          this.props.dispatch({type: "SET_ERROR", payload: error.message})
          this.props.dispatch({type: "STOP_LOADER"})
        },
        { enableHighAccuracy: true, distanceFilter: 200, interval: 1000, fastestInterval: 1000}
      ),
    })
```

Unfortunately, even with the option `interval` the location is not updated after 10 seconds. I can see that because the dispatch prints an output on the app's screen and it appears only the first time that  I mount the component.

How can I fix this?

Just for reference: it doesn't update even if I'm keeping the app open and the screen active.

**Comment by Agontuk** [comment]
Can you try the example app and see if it has the same issue ?

**Comment by Agontuk** [comment]
Just realised you set the distanceFilter to 200, so unless you're moving location will not update. Closing this for now, feel free to open new issue if problem persists.
