### ISSUE TITLE
Please remove warning - Called stopObserving with existing subscriptions

### ISSUE THREAD

**Issue by cristianoccazinsp** [Agontuk/react-native-geolocation-service#149]
https://github.com/Agontuk/react-native-geolocation-service/blob/master/js/Geolocation.android.js#L87

Even if we call `clearWatch` before `stopObserving`, this warning is fired every time and gets very annoying. Can we get the warning removed? Or what's the right way to prevent it?

**Comment by tylerolechnowicz** [comment]
I can also attest to this...The warning is fired every time even if `clearWatch` is called before `stopObserving`

**Comment by Agontuk** [comment]
Sorry for the late reply, you do not need to call `stopObserving`, `clearWatch` will call it if there's no watchers left. That means you must have multiple watchers subscribed, some of which are not cleared yet. That's why you're getting warning.

**Comment by himat** [comment]
@Agontuk just to confirm, I can just call `stopObserving` and never need to call `clearWatch` right? Since `stopObserving` should remove all watchers by itself?

**Comment by Agontuk** [comment]
> @Agontuk just to confirm, I can just call `stopObserving` and never need to call `clearWatch` right? Since `stopObserving` should remove all watchers by itself?

It's the other way around. You should call only `clearWatch`, and it'll call `stopObserving` if there's no watchers running.

**Comment by n0f3** [comment]
hi @Agontuk, If I only use clearWatch, after component is unmount, the location is still being tracked, so I'm forced to using stopObserving, and the warnings are still showing. Is this expected behavior?

**Comment by louisobasohan** [comment]
i have same experience with @n0f3, is this expected behaviour?

**Comment by Agontuk** [comment]
> hi @Agontuk, If I only use clearWatch, after component is unmount, the location is still being tracked, so I'm forced to using stopObserving, and the warnings are still showing. Is this expected behavior?

Can you provide a sample code ? This shouldn't be possible, clearWatch removes location tracking when called.

**Comment by alessandro-bottamedi** [comment]
Same problem here, even if I execute clearwatch the localization remains active until I execute stopObserving, but the warning appears

**Comment by vladiulianbogdan** [comment]
> > @Agontuk just to confirm, I can just call `stopObserving` and never need to call `clearWatch` right? Since `stopObserving` should remove all watchers by itself?
> 
> It's the other way around. You should call only `clearWatch`, and it'll call `stopObserving` if there's no watchers running.

The documentation for stopObserving() says: "Stops observing for device location changes. In addition, it removes all listeners previously registered.". From this I understand that if there are some listeners, they will be removed when stopObserving() is called. Am I misinterpreting this?

**Comment by Agontuk** [comment]
> The documentation for stopObserving() says: "Stops observing for device location changes. In addition, it removes all listeners previously registered.". From this I understand that if there are some listeners, they will be removed when stopObserving() is called. Am I misinterpreting this?

No you're right.

`clearWatch` will clear a specific subscription and then check if there's any active watcher. If there's none, it'll call `stopObserving` to shut down the native location updates.

`stopObserving` will shut down the native location updates immediately, then proceeds to check if there's any active watchers. If there are active watchers, it'll print a warning to let developers know they still have active watchers before clearing all of them.

Printing the warning is actually useful for developers, who mistakenly called `stopObserving`.  If you're knowingly calling it to stop location updates & getting annoyed with the warning, you can ignore it using `YellowBox` api. Also this only affects development, it has no effect in production.

**Comment by vladiulianbogdan** [comment]
That makes sense! Great, thank you for clarification and for your work!
