### ISSUE TITLE
can't work with react native 0.60.0 althought it's working in react-native-geolocalisation 

### ISSUE THREAD

**Issue by ISLEMNEDDAR** [Agontuk/react-native-geolocation-service#152]
when installing the package we have in the build the error of missing error : error, string, array 
with react native 0.60.0
but the react-native-geolocalisation it's working good are they the same?

**Comment by zhitomir-oreshenski-mm** [comment]
Hi,

Same here.

**Comment by ISLEMNEDDAR** [comment]
i see that they are the same packages and the react-native-geolocalisation work good in the new version of react so you can switch the the other package
