### ISSUE TITLE
Beware of time APIs...

### ISSUE THREAD

**Issue by wynch** [Agontuk/react-native-geolocation-service#16]
I was reading your module source code - I'm not using it currently - but I noticed something that might cause a bug...

This was inspired by this talk from Runkeeper developer : https://speakerdeck.com/pconno3/the-struggles-with-location-services

He mentions a difficult bug they had on some android devices, when using `System` current time : your system time CAN change when different cell-towers provide different times, that update system time..

This is indeed what `Location` documentation says  (https://developer.android.com/reference/android/location/Location.html#getTime() ) 

` "Note that the UTC time on a device is not monotonic: it can jump forwards or backwards unpredictably. So always use getElapsedRealtimeNanos() when calculating time deltas." `)

I thought you might want to know that ;)

**Comment by Agontuk** [comment]
Thanks for the report, I'll take a look at the urls you provided and do a quick fix :)

**Comment by Agontuk** [comment]
This is now fixed for newer android versions in [here](https://github.com/Agontuk/react-native-geolocation-service/blob/1fb807ec636f262de94a95c14b2e3cc873998520/android/src/main/java/com/agontuk/RNFusedLocation/LocationUtils.java#L26-L32). Thanks for reporting this, sorry it took this long.
