### ISSUE TITLE
SuccessCallback Details are Missing in the Documentation

### ISSUE THREAD

**Issue by samitha9125** [Agontuk/react-native-geolocation-service#169]
Hi all,

First of all I would like to thank to all people who made this library. This is an awesome work and thank you guys. 

My issue is that the Documentation/Readme of this library lacks some explanation of successCallback details such as what does speed means, how it gets calculated, unit of the speed value ...etc. 

It would be awesome if someone can add these to the documentation and explain how speed calculation carryout in this library.

**Comment by Agontuk** [comment]
This library does not calculate any of the result it emits. You have to read the android & ios documentation respectively to know how they're calculated.

Here is the android doc [https://developer.android.com/reference/android/location/Location#getAccuracy()](https://developer.android.com/reference/android/location/Location#getAccuracy())
