### ISSUE TITLE
CurrentPosition always the default

### ISSUE THREAD

**Issue by gunnx** [Agontuk/react-native-geolocation-service#170]
Possibly I've just missed something really simple but when I request currentPosition it always returns   {"latitude": 37.42342342342342, "longitude": -122.08395287867832} 

I've tried setting location via the Location option in the emulator and also by trying `geo fix` from telnet but no change.
If I open Google Maps on the emulator it defaults to the correct location, so I kinda know that must be working fine.

Code that I'm using

```
 Geolocation.getCurrentPosition(
      (position: GeoPosition) => {
        setInitialRegion({
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          latitudeDelta: 0.0922,
          longitudeDelta: 0.0421,
        })
        setMapReady(true)
      },
      error => {
        setInitialRegion(defaultRegion)
        setMapReady(true)
      },
      {
        enableHighAccuracy: false,
        timeout: 5000,
        maximumAge: 3000,
      },
    )
```

Hoping someone else knows the issue? Thanks

**Comment by shacharbuda** [comment]
We (@idonov8 and I) just got with the same issue.
the maximumAge option decides how long will the last location retrieved will be stored in cache.
If you wish to always get the location from the location service origin (not cache),
All you need to do is add an option 
```{ maximumAge: 0 }```

**Comment by pavermakov** [comment]
@shacharbuda this is not working on ios

**Comment by Agontuk** [comment]
> Possibly I've just missed something really simple but when I request currentPosition it always returns {"latitude": 37.42342342342342, "longitude": -122.08395287867832}

It's working fine here. I can change the location from emulator settings and it's being reflected properly in `getCurrentPosition` response.

**Comment by Agontuk** [comment]
It's emulator problem. Possible fix is to open google maps at least once, or restart the emulator once. Then it should work properly.
