### ISSUE TITLE
watchPosition ID

### ISSUE THREAD

**Issue by ezos86** [Agontuk/react-native-geolocation-service#171]
How can I get the id of the watchPosition to clear it? Seems like it's not returned.

Surprised this has not come up.

**Comment by Agontuk** [comment]
Yes, it's returned after calling watchPosition. Please check again.

**Comment by ezos86** [comment]
Nope @Agontuk. See Screenshots

![image](https://user-images.githubusercontent.com/1334598/79277242-4b164e00-7e5e-11ea-98c7-d12cb952b371.png)


![image](https://user-images.githubusercontent.com/1334598/79277220-3f2a8c00-7e5e-11ea-98c6-f77ad3032230.png)

**Comment by Agontuk** [comment]
Not the response, the function itself returns the id.
```js
const id = Geolocation.watchPosition(...);
```

**Comment by ezos86** [comment]
@Agontuk Thank you.
