### ISSUE TITLE
RN v0.62.2  - No podspec file was found.

### ISSUE THREAD

**Issue by orhanoksuzz** [Agontuk/react-native-geolocation-service#175]
I am getting the Podspec file not found error. Can you help me?

<img width="575" alt="Ekran Resmi 2020-05-01 05 01 43" src="https://user-images.githubusercontent.com/16277060/80775620-dc790600-8b68-11ea-8ce2-88abc25d99b7.png">

**Comment by Agontuk** [comment]
It's because this library has ios module, it uses the @react-native-community/geolocation package for ios. But I'm implementing ios module, so you should try out this branch [https://github.com/Agontuk/react-native-geolocation-service/tree/next](https://github.com/Agontuk/react-native-geolocation-service/tree/next). Feedbacks are welcome.

You can track the progress here [https://github.com/Agontuk/react-native-geolocation-service/issues/173](https://github.com/Agontuk/react-native-geolocation-service/issues/173)

**Comment by jplew** [comment]
One installs that branch like this, right?

`npm install git://github.com/Agontuk/react-native-geolocation-service.git#next`

**Comment by Agontuk** [comment]
> One installs that branch like this, right?
> 
> `npm install git://github.com/Agontuk/react-native-geolocation-service.git#next`

Yes, that should work fine. Do let me know if you've any suggestion or face any problem. Closing the issue for now, I'll be merging this into master branch soon.

**Comment by OlivierVoyer** [comment]
Hi @Agontuk , I tried to checkout your new next branch to test the issue I had before with your library but unfortunately, I can't have `pod install` working as i get the same error message:

```
Detected React Native module pod for react-native-geolocation-service
Analyzing dependencies
[!] No podspec found for `react-native-geolocation` in `../node_modules/@react-native-community/geolocation`
```

Please find attached a test project using that next branch in package.json

[MyApp.zip](https://github.com/Agontuk/react-native-geolocation-service/files/4708091/MyApp.zip)

**Comment by OlivierVoyer** [comment]
@Agontuk : Same missing podspec issue with "react-native-geolocation-service": "^5.0.0" in my package.json.
It looks like a missing dependency that can be manually fixed by running `yarn add @react-native-community/geolocation`.
Maybe only adding it to the README could be an acceptable fix.

**Comment by Agontuk** [comment]
> @Agontuk : Same missing podspec issue with "react-native-geolocation-service": "^5.0.0" in my package.json.
> It looks like a missing dependency that can be manually fixed by running `yarn add @react-native-community/geolocation`.
> Maybe only adding it to the README could be an acceptable fix.

No, it means you're still requiring this from your Podfile or somewhere else. This dependency was removed in v5.0.0. It's not needed.

**Comment by OlivierVoyer** [comment]
You're 100% right. Sorry, my mistake.
A reference was still present in my Podfile.
Thanks for your support
