### ISSUE TITLE
Update @react-native-community/geolocation dependency to latest

### ISSUE THREAD

**Issue by smsmdida** [Agontuk/react-native-geolocation-service#179]
Hey,

i noticed that 
@react-native-community/geolocation is set to 1.4..
the latest is 2.0.1
any reason of this ? or can i create a PR to update it ?

**Comment by Agontuk** [comment]
There's no ios changes from 1.4 to 2.0.1, so it's not needed. Also I'll be removing `@react-native-community/geolocation` dependency in the next version. See the progress here #173
