### ISSUE TITLE
4.0.1 warning

### ISSUE THREAD

**Issue by cristianoccazinsp** [Agontuk/react-native-geolocation-service#180]
Updating from 4.0.0 to 4.0.1 is raising the following warning, can you silence this somehow?

`[!] use_native_modules! skipped the react-native dependency 'react-native-geolocation-service'. No podspec file was found.`

Lastly, could the dependency to @react-native-community/geolocation be made a peer dependency? Otherwise, the library ends up installed twice.

**Comment by Agontuk** [comment]
Try `rm -rf node_modules/react-native-geolocation-service/ios`. ios folder was mistakenly added when publishing to npm.

Why @react-native-community/geolocation is installed twice ? You shouldn't add it as a dependency in your package.json.

**Comment by cristianoccazinsp** [comment]
I'm almost sure I tried deleting the folder, but the iOS folder came back somehow.

About the duplicate, perhaps I'm wrong and it only gets installed once, but I had to make some fixes to the iOS version of @react-native-community/geolocation, so I need to install it from my fork/github.  Now that I think of, even if it is listed as a dependency, the native code should be installed only once right?

**Comment by Agontuk** [comment]
> I'm almost sure I tried deleting the folder, but the iOS folder came back somehow.
> 
> About the duplicate, perhaps I'm wrong and it only gets installed once, but I had to make some fixes to the iOS version of @react-native-community/geolocation, so I need to install it from my fork/github. Now that I think of, even if it is listed as a dependency, the native code should be installed only once right?

There can be duplicate packages in node_modules with different versions, but react-native will use only one automatically or that you pointed in podfile.

**Comment by jbolotin** [comment]
Thanks for the great library, @Agontuk. Is it possible to release a new version with `node_modules/react-native-geolocation-service/ios` removed? I followed your instructions, and it does fix the problem for me, but it took a bit of hunting to find this issue, and I imagine everyone updating to 4.0.1 will experience the same problem.

**Comment by orzhtml** [comment]
[!] use_native_modules! skipped the react-native dependency 'react-native-geolocation-service'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec.
    See https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

**Comment by Agontuk** [comment]
4.0.2 published, should fix the issue.
