### ISSUE TITLE
watchPosition is not working when location is changed 

### ISSUE THREAD

**Issue by mukash** [Agontuk/react-native-geolocation-service#184]
i am using watchposition for real time tracking but it response only once then its not working. Kindly help me out in it.
 
this is the code please tell me where am i wrong.

![Screenshot_3](https://user-images.githubusercontent.com/41724730/84750664-05e4d880-afd5-11ea-8767-e827e927b274.png)

**Comment by Agontuk** [comment]
Set `distanceFilter` to 0 or lower value to get frequent update.

**Comment by mukash** [comment]
thankyou.
