### ISSUE TITLE
Not working with latest Xcode version 11.5

### ISSUE THREAD

**Issue by reactnative103** [Agontuk/react-native-geolocation-service#192]
I have download the latest Xcode-11.5 and It ask me for permission but give always "POSITION_UNAVAILABLE".

My Info.plist:

<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>desc</string>
<key>NSLocationAlwaysUsageDescription</key>
<string>desc</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>desc</string>

Note: It is working fine with the previous Xcode -10.3.

Please help me to out due to this unexpected things.

**Comment by reactnative103** [comment]
I found solution for this.

**Comment by AdamLee321** [comment]
You should leave the solution in case someone else has this issue
