### ISSUE TITLE
is it working when app killed in ios?

### ISSUE THREAD

**Issue by lyseiha** [Agontuk/react-native-geolocation-service#193]

**Comment by lyseiha** [comment]
When i use **useSignificantChanges** the app is working but until more than 5 mins and moving.

**Comment by Agontuk** [comment]
Please read the apple documentation, useSignificantChanges only provides location when significant movement is detected.

[https://developer.apple.com/documentation/corelocation/cllocationmanager/1423531-startmonitoringsignificantlocati](https://developer.apple.com/documentation/corelocation/cllocationmanager/1423531-startmonitoringsignificantlocati)

**Comment by lyseiha** [comment]
Thank you. but do you have a way to decrease from 500meter to something like 100 meters or 200 meters.

**Comment by Agontuk** [comment]
Nope, apple sdk does not expose any property to change this.

**Comment by lyseiha** [comment]
But do you plan to research and do on this lib for that feature, bro?

**Comment by lyseiha** [comment]
do you have any update on this yet, sir?
