### ISSUE TITLE
Enable enableHighAccuracy in iOS only returns position after timeout

### ISSUE THREAD

**Issue by mllrmat** [Agontuk/react-native-geolocation-service#197]
With build 5.0 and `enableHighAccuracy=true` the position on iOS devices is only returned after the timeout is reached. Im my case this is after 10 seconds. When I disable enableHighAccuracy it works fine. This is a new behaviour with build 5. Before it worked as expected. 
This only happens on real devices. In the simulator it immediately returns the location. 
I am using the following options for getCurrentPosition: 
```
{
  distanceFilter: 100,
  enableHighAccuracy: true,
  timeout: 10000,
  maximumAge: 60 * 5 * 1000
}
```
I tested this on several iOS devices and the behaviour is the same.

**Comment by Agontuk** [comment]
I don't have ios devices, so can't verify this. Can you try setting distanceFilter to 0 and see if it solves the problem ?

**Comment by elirangoshen** [comment]
I have the sam issue.. location took me in ios device 9 seconids to get.. 
hmm wonder why is it so slow ?  +1

**Comment by FadiAboMsalam** [comment]
Same issue here. any solutions yet

**Comment by ravirajn22** [comment]
My config is `{ enableHighAccuracy: true, timeout: 25000, maximumAge: 0, distanceFilter: 10, showLocationDialog: false};`

But I always get the first location update within 0 - 2 sec. But I use `Geolocation.watchPosition` not `Geolocation. getCurrentPosition`. @FadiAboMsalam @elirangoshen can u also confirm that you have this issue while using `Geolocation. getCurrentPosition` ?

**Comment by WGoinz** [comment]
Experiencing this with iOS as well in RN 63.2

**Comment by Agontuk** [comment]
In previous version, we used `startUpdatingLocation` for both `getCurrentPosition` & `watchPosition`. In v5, `getCurrentPosition` was changed to use `requestLocation` method from native ios library. I'm not sure, but this is probably causing the delay.

**Comment by WGoinz** [comment]
@mllrmat did you find a workaround for your issues?

**Comment by Agontuk** [comment]
I tested with an iPhone 8 plus device and only faced this delay when I'm inside my room with door & windows closed. Otherwise I get location within 3-4 seconds max. So I don't think it's an issue with the current version of the library.

**Comment by lifenautjoe** [comment]
Anyone has found more information on the reason for this? This error is pretty consistent over here...

**Comment by creat-or** [comment]
I have the same problem, iOS14, RN0.63

**Comment by inepineee** [comment]
Same problem here with version 5.0.0, RN 0.63.2. Works as expected on simulator, but not on real device. Tested real devices with iOS12, iOS13 and iOS14. 

Did not get position at all having a timeout below 10 seconds. Increased the timeout to 10 seconds and now I experience exactly the same, as soon as timeout error is thrown the position is returned. 

Works for me as well setting enableHighAccuracy to false.

**Comment by ravirajn22** [comment]
Went through `requestLocation` iOS docs which this library uses for `getCurrentPosition`. According to them, this function will try to get GPS data for the accuracy set. Under the hood enableHighAccuracy uses `kCLLocationAccuracyBest` which is the highest accuracy possible. GPS algorithms use lot of data to calculate GPS position like wifi, bluetooth, mobile signal and GPS. Hence calculating GPS location with accuracy `kCLLocationAccuracyBest` will vary from place to place.

According to the docs it will return GPS location if it satisfies the desired accuracy or after timeout.
Hence for your error cases it looks like the device is taking around 10 sec to get the desired accuracy, so this delay.

Earlier this library used to start a GPS continuous update request and will stop on first result and send the response in `getCurrentPosition`. This should have returned first location earlier, but this might not be of required accuracy. This is how continuous GPS location request works.

So, you have two options to solve this problem,
1. Lower your timeout and hope you get the desired accuracy. Better solution than using `enableHighAccuracy:false` (which will use like city level accuracy).
2. Start watchPosition urself and stop, kind of complicated for simple use cases but still you have the option.

There are other accuracy options in iOS native API, but that is not supported in this library.

**Comment by inepineee** [comment]
> Went through `requestLocation` iOS docs which this library uses for `getCurrentPosition`. According to them, this function will try to get GPS data for the accuracy set. Under the hood enableHighAccuracy uses `kCLLocationAccuracyBest` which is the highest accuracy possible. GPS algorithms use lot of data to calculate GPS position like wifi, bluetooth, mobile signal and GPS. Hence calculating GPS location with accuracy `kCLLocationAccuracyBest` will vary from place to place.
> 
> According to the docs it will return GPS location if it satisfies the desired accuracy or after timeout.
> Hence for your error cases it looks like the device is taking around 10 sec to get the desired accuracy, so this delay.
> 
> Earlier this library used to start a GPS continuous update request and will stop on first result and send the response in `getCurrentPosition`. This should have returned first location earlier, but this might not be of required accuracy. This is how continuous GPS location request works.
> 
> So, you have two options to solve this problem,
> 
> 1. Lower your timeout and hope you get the desired accuracy. Better solution than using `enableHighAccuracy:false` (which will use like city level accuracy).
> 2. Start watchPosition urself and stop, kind of complicated for simple use cases but still you have the option.
> 
> There are other accuracy options in iOS native API, but that is not supported in this library.

Nice investigation. In my case I am not able to get any location with a timeout lower than 10 seconds so I don't think that's an option, for us at least. But with the enableHighAccuracy flag disabled I still get pretty accurate addresses. Right now we have disabled it only for iOS, and I actually get the same results on iOS as we do on Android where we have the flag on. 

Does anybody experience low accuracy with the flag disabled?

**Comment by Agontuk** [comment]
@ravirajn22 thanks for your detailed explanation.

Since it's not an implementation issue, I think the best solution is to expose other accuracy options to the developer and let them pick whatever suits their needs.

**Comment by ravirajn22** [comment]
Yes, better we expose it. But we should make feature parity with android. Accuracy options must be simple strings. For example, https://github.com/baseflow/flutter-geolocator (Just for sample, don't know if all location accuracy options should be exposed). A research on various platform (macOS, windows, Android etc) GPS options should give us an idea.

**Comment by Agontuk** [comment]
Took a look at both ios & android docs, probably expose a key like this:
```js
...
accuracy: {
  ios: string,
  android: string,
}
...
```

Where `ios` value will be one of
```
'bestForNavigation',
'best',
'nearestTenMeters',
'nearestHundredMeters',
'nearestKilometer',
'nearestThreeKilometers',
'reduced'
```

And `android` will be one of
```
'high',
'balanced',
'low',
'passive'
```

**Comment by ravirajn22** [comment]
~'bestForNavigation',~
'best', (high power in android)
~'nearestTenMeters'~,
'hundredMeters', (balanced power in android)
'kilometer', (balanced power in android)
~'threeKilometers'~
'lowest' (kCLLocationAccuracyReduced in iOS and  low power in android)

IMO, use cases of `nearestTenMeters` should be satisfied by `best`. Also `kilometer` vs `threeKilometers`, any one should satisfy the others use case easily.

We can for now skip bestForNavigation which is iOS only (Lets consider if someone requests). We can also skip `passive` in android, I never found its use case.

Both iOS and Android will use the same constants.
```
'best',
'hundredMeters',
'kilometer',
'lowest'
```

Do you think the above API will work? I am also little confused between using common constants between iOS and Android vs using platform specific constants.

For common constants,
1. Easier to use API, documentation
2. Most of open source GPS library use common constants instead of platform specific

Against common constants,
1. We could be abstracting without knowing all the cases.

**Comment by Agontuk** [comment]
@ravirajn22 ,  If we intend to expose accuracy levels, we should expose all of them. Grouping them together will create problem later when new accuracy level is exposed from the native platform. For example, in ios 14 there is a new accuracy constant named `kCLLocationAccuracyReduced `.

About the API we can use either of the following:

```js
accuracy: {
  ios: 'best',
  android: 'high',
}

// or

accuracy: Platform.OS === 'ios' ? 'best' : 'high'
```

Which one you think is better ?

**Comment by ravirajn22** [comment]
For me both API look good to me.

For now we don't support any other platform other than iOS and android, so the below API should work and be simple. 

`accuracy: Platform.OS === 'ios' ? 'best' : 'high'`

**Comment by rayj10** [comment]
hey guys, just stumbled upon this and in my area, location update has always been slow (my city's average connections speed sucks)
I've been using timeout 15 seconds even with the older versions, and as soon as I updated to 5.0.0, the 15 seconds doesn't even cut it anymore.

I saw u guys already started planning on exposing more options. thanks for that, but while waiting for that, what would you suggest is the fastest way to adapt this to my case?
also sorry for the noob question, but what would setting `maximumAge: 0` and `distanceFilter: 10` means?
I've always put `maximumAge: 60000` because I assumed I want the cached location to expire in 60 seconds and ask for a new one, but i never tried  setting it to a number way lower than the timeout itself.

thanks in advance :)

**Comment by Agontuk** [comment]
@rayj10 you can use the master branch to try out `accuracy` option, it's already implemented. API may change, so use it only to test the feature.

setting maximumAge to `N` means for the next `N/1000` seconds if you request location, it'll return the previous result.

setting distanceFilter to `N` means it'll notify location change only when user moves at least `N` meter

**Comment by rayj10** [comment]
> @rayj10 you can use the master branch to try out `accuracy` option, it's already implemented. API may change, so use it only to test the feature.
> 
> setting maximumAge to `N` means for the next `N/1000` seconds if you request location, it'll return the previous result.
> 
> setting distanceFilter to `N` means it'll notify location change only when user moves at least `N` meter

Thankyou so much for the explanation! will try out the accuracy option soon! 👍

**Comment by sataporn8063** [comment]
hey I have a problem about getCurrentPosition is taking longtime ~10(S) anyone find this problem?

**Comment by ravirajn22** [comment]
@Agontuk what is the status? can we release it to public as beta. Do you require any help?

**Comment by Agontuk** [comment]
> @Agontuk what is the status? can we release it to public as beta. Do you require any help?

Sorry I was busy with my job. Accuracy options are already implemented, just need to expose them in js side.

**Comment by Agontuk** [comment]
v5.1.0 published with accuracy level support, doc has been updated.

**Comment by alexandersandberg** [comment]
@Agontuk Is there a reason why an option for `kCLLocationAccuracyReduced` on iOS has been left out from the new accuracy options?

Also, if Precise Location is disabled, would another level of accuracy, e.g. `best` (`kCLLocationAccuracyBest`), fall back to `kCLLocationAccuracyReduced`?

**Comment by ravirajn22** [comment]
Thanks for the work,

@Agontuk 
`enableHighAccuracy` option should be removed and a new major version must be released, so that people don't get confused and less maintenance.

@alexandersandberg 

> Also, if Precise Location is disabled, would another level of accuracy, e.g. best (kCLLocationAccuracyBest), fall back to kCLLocationAccuracyReduced?

YES.

`kCLLocationAccuracyReduced` option should be added. PR is welcome from anyone.

**Comment by Agontuk** [comment]
> @Agontuk Is there a reason why an option for `kCLLocationAccuracyReduced` on iOS has been left out from the new accuracy options?

It'll be added when precise location related features are integrated.
 
> Also, if Precise Location is disabled, would another level of accuracy, e.g. `best` (`kCLLocationAccuracyBest`), fall back to `kCLLocationAccuracyReduced`?

Yes.

> `enableHighAccuracy` option should be removed and a new major version must be released, so that people don't get confused and less maintenance.

It's there for the web support and backward compatibility.

**Comment by Agontuk** [comment]
`kCLLocationAccuracyReduced` is supported only in iOS 14. For iOS < 14, should we fall back to use `threeKilometers` ?

**Comment by Agontuk** [comment]
Closing this as the fix is already available in new versions. Thanks everyone for their feedbacks.
