### ISSUE TITLE
iOS App Store Build Missing Purpose String

### ISSUE THREAD

**Issue by gitschwifty** [Agontuk/react-native-geolocation-service#198]
I'm just using whenInUse in my application yet every build I submit to the App Store gets me a warning from them on a missing purpose string for NSLocationAlwaysUsageDescription:

> ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

I haven't had any issues with testing it, and it doesn't ask for Always permission nor does it have it granted in settings. Do I just need to add the UsageDescription anyways, or is there something I'm missing here? Saw `Geolocation.setRNConfiguration` in some older closed issues but it doesn't seem to be available in the API anymore. Sorry to bother if it's just something you have to add whether or not it's used.

**Comment by ravirajn22** [comment]
This library has code to use both whenInUse and Always. It's a known thing in app store that you have to include strings even if you don't call that permission. Just add the string and you should be good to go. Google it for further details there are already many discussions on this.

**Comment by gitschwifty** [comment]
Works for me, thanks, wasn't sure since I couldn't find anything specific on it on Google

**Comment by Agontuk** [comment]
I'll update the doc, right now it does not mention this.
