### ISSUE TITLE
Is there any limitation for this package for the android platform version?

### ISSUE THREAD

**Issue by Shhzdmrz** [Agontuk/react-native-geolocation-service#2]
Hello,
First of all thank you so much for this awesome plugin for android as I was dealing with timeout problem with navigator.geolocation.

As you are using this condition in your example `Platform.Version < 23` so what is that mean? Is there any limitation for this plugin? I am not an android developer but learning react native so could you please explain this.

thank you in advance.

**Comment by Agontuk** [comment]
No, it's not a limitation. Android runtime permission is only needed for API level 23 or above, below that permissions are automatically granted during app installation. That check is only to make sure app has location permission before making a location request.

**Comment by Shhzdmrz** [comment]
ahh great thanks man.

**Comment by antonioreyna** [comment]
how do i check the permission on android

**Comment by oakis** [comment]
@antonioreyna https://facebook.github.io/react-native/docs/permissionsandroid
