### ISSUE TITLE
Is it not possible to use this library for mobile phones without google play service?

### ISSUE THREAD

**Issue by ShaoGongBra** [Agontuk/react-native-geolocation-service#203]
Most of China does not have google play service

**Comment by Agontuk** [comment]
Unfortunately no, this library currently depends on the google-play-service-location package.

**Comment by kasbah** [comment]
Would it be possible to fall back to using AOSP location if Play Services aren't installed?

**Comment by Agontuk** [comment]
> Would it be possible to fall back to using AOSP location if Play Services aren't installed?

It's possible, but that's not implemented yet. It's kind of a big change, so it may take some time.

**Comment by Agontuk** [comment]
This currently a work in progress, you can track the progress [here](https://github.com/Agontuk/react-native-geolocation-service/tree/android-rewrite)

**Comment by TommyLeong** [comment]
Hi @Agontuk, can I assume the AOSP location is not depending on Play Services as @kasbah mentioned? Pretty new to Android, kindly correct if I've understood wrongly.

Hence [your work here](https://github.com/Agontuk/react-native-geolocation-service/compare/android-rewrite) is actually creating ...

1. A provider using [FusedLocationProviderClient](https://github.com/Agontuk/react-native-geolocation-service/compare/android-rewrite#diff-4744927d24b0a111d526c74a83abd6501eaa1d37fa17ed0bb52955f581a80b83R16) (which user in China won't be able to user)

2. Another provider using [android.location.LocationManager](https://github.com/Agontuk/react-native-geolocation-service/compare/android-rewrite#diff-8b26d3130fc518cb979ef057afdae15e54fd88906f619bea788690c524f909b2R8) which is a fallback solution to user in China? - which is the AOSP? 

Have I understand that correctly?

**Comment by Agontuk** [comment]
@TommyLeong , yes that's correct. This implementation will check if google play service is available on device, then use the correct provider based on that. Here's the relevant code
[https://github.com/Agontuk/react-native-geolocation-service/blob/android-rewrite/android/src/main/java/com/agontuk/RNFusedLocation/RNFusedLocationModule.java#L105-L113](https://github.com/Agontuk/react-native-geolocation-service/blob/android-rewrite/android/src/main/java/com/agontuk/RNFusedLocation/RNFusedLocationModule.java#L105-L113)

**Comment by Agontuk** [comment]
The implementation is done, you can try using the [`android-rewrite`](https://github.com/Agontuk/react-native-geolocation-service/tree/android-rewrite) branch to test it out.

**Comment by Agontuk** [comment]
Closing this, as it's already available in new version
