### ISSUE TITLE
getPosition() returning cached data instead of current location

### ISSUE THREAD

**Issue by arumsey93** [Agontuk/react-native-geolocation-service#205]
I am running into an issue where cached geolocation data is being returned instead of the current geolocation data. It is my understanding that the previous geolocation should be wiped once the maximumAge has reached the end of its countdown.  Currently, the maximumAge is set to 0, but I tried a few different variations of 1000-10000 to attempt to refresh the cache and remove the previous geolocation, is there a fix out there that I am overlooking for this or does this problem tend to occur in an iOS simulator.

```  
const getPosition = () => {
    if (fetchingLocation === true) {
      return;
    } else {
      setFetchingLocation(true);
    }
    Geolocation.getCurrentPosition(
      (position) => {
        setGeoLocation(position?.coords);
        setFetchingLocation(false);
        console.log('setGeolocation', position?.coords);
      },
      (error) => {
        setGeoLocation(null);
        setFetchingLocation(false);
        console.log('geolocation error');
      },
      {enableHighAccuracy: true, timeout: 0, maximumAge: 0},
    );
  };```

**Comment by iamjon** [comment]
I can confirm that I'm having the same issue in IOS. Setting distanceFilter:10 also doesn't help

**Comment by Agontuk** [comment]
Simulator always provides a fixed static location unless you configure it from `Features -> Location` menu. There you can change location to use `Bicycle Ride`/`Freeway Drive` etc and then simulator will start providing different locations.

But it's better to test this in a real device.

**Comment by sgade** [comment]
Having the same problem.

Using `getCurrentPosition` returns the custom location in the simulator.
If I change the location in the simulator between calls it still returns old data (timestamp is the same etc).
Would expect a different location after 10 mins.

Putting the app in the background helps, sometimes. Getting called on my callback then, even though I removed the watch (which might be another problem but still it updates the location on entering foreground).

**Comment by Agontuk** [comment]
Can you check if this happens on a real device too ? Also is it only ios specific ?

**Comment by redwind** [comment]
> Can you check if this happens on a real device too ? Also is it only ios specific ?

I confirm that it happens on real device. When getCurrentPosition, it got cached location without update latest location, but if we open GoogleMap, then getCurrentPosition, it return newest location

**Comment by ferasabufares** [comment]
@redwind  did you find any solution? i have the same problem 

```
   "react": "^17.0.1",
    "react-native": "^0.63.4",
"react-native-geolocation-service": "^4.0.0"
``` 

this is my code but still i got cached location 

```
async _getCurrentLocation() {
  if (Platform.OS == 'android') {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
    );
    if (granted == 'granted') {
      await Geolocation.getCurrentPosition(
        (position) => {
          this.setState(
            {
              LATITUDE: position.coords.latitude,
              LONGITUDE: position.coords.longitude,
            },
            () => {
              if (position.coords.latitude) {
                setTimeout(() => {
                  //call api
                }, 500);
              }
            },
          );
        },
        (errorCallback) => {
       
        },
        {
          enableHighAccuracy: true,
          timeout: 15000,
          maximumAge: 0,
          forceRequestLocation: true,
        },
      );
    } 
  } else {
    await Geolocation.requestAuthorization();
    await Geolocation.setRNConfiguration({
      skipPermissionRequests: false,
      authorizationLevel: 'whenInUse',
    });

    await Geolocation.getCurrentPosition(
      (position) => {
        this.setState(
          {
            LATITUDE: position.coords.latitude,
            LONGITUDE: position.coords.longitude,
          },
          () => {
            if (position.coords.latitude) {
              setTimeout(() => {
                //call api
              }, 500);
            } else {}
          },
        );
      },
      (errorCallback) => { },
      {
        enableHighAccuracy: true,
        timeout: 15000,
        maximumAge: 0,
      },
    );
  }
}
```

**Comment by ferasabufares** [comment]
> Can you check if this happens on a real device too ? Also is it only ios specific ?

 it is happenes in real device both android and ios

**Comment by khushbooOpenxcell** [comment]
I too have the same pronlem.

**Comment by seanluse41** [comment]
Having the same problem, react native on android device.
```
        "react": "16.13.1",
        "react-i18next": "^11.3.3",
        "react-native": "0.62.1",
        "react-native-android-location-enabler": "^1.2.1",
        "@react-native-community/geolocation": "^2.0.2",
```

usage:
```

    useEffect(() => {
        Geolocation.getCurrentPosition(
            (position) => {
                const tempInitialCamera = {
                    center: {
                        latitude: position.coords.latitude,
                        longitude: position.coords.longitude,
                    },
                    pitch: 0,
                    heading: 0,
                    altitude: 0,
                    zoom: configuration.defaultZoom,
                }
                if (!isScrollMap) {
                    setCurrentCamera({camera: tempInitialCamera, zoom: configuration.defaultZoom})
                }
                setCurrentPosition(position.coords)
            },
            (error) => {
                alert(JSON.stringify(error))
                console.log(error)
            },
            {enableHighAccuracy: true, timeout: 10000},
        )
        const watchID = Geolocation.watchPosition(
            (position) => {
                const tempInitialCamera = {
                    center: {
                        latitude: position.coords.latitude,
                        longitude: position.coords.longitude,
                    },
                    pitch: 0,
                    heading: 0,
                    altitude: 0,
                    zoom: configuration.defaultZoom,
                }
                if (!isScrollMap) {
                    setCurrentCamera({camera: tempInitialCamera, zoom: configuration.defaultZoom})
                }
                setCurrentPosition(position.coords)
                // if (!isScrollMap) {
                //     focusLocation(true)
                // }
            },
            (error) => console.log(error),
            {enableHighAccuracy: true, distanceFilter: 1, interval: 200, fastestInterval: 200},
        )
        return () => {
            Geolocation.clearWatch(watchID)
        }
    }, [])
```

appears to occur after a set amount of time.

**Comment by ua-lock** [comment]
### Workaround (Android only):
_Ps.: the steps for IOs devices should be mostly the same, I didn't test it though, as I don't have one_
_Ps2: this was tested in Android API 30, the process remains the same but navigation may vary depending on your device's api version_

1. As others have mentioned, make sure you have set the desired location in the emulator settings;
2. Close your app instance;
3. In the emulated device, navigate to it's "Settings" (usually the cog icon in the app menu);
4. Navigate to "Apps & notifications", then select your app in the list of apps;
5. Navigate to "Storage & cache";
6. Click "Clear storage" as it'll also clear cached data;

That should do it, re-launch your application and your location/coordinates should now be updated. Just to make sure, I added the `{ maximumAge: 0 }` option to my `getCurrentPosition()` call, but you can change that number to something more reasonable.

**Comment by anwar-kt** [comment]
I my case the issue found only in simulator (API 30) not in the phone (android 11).

**Comment by RonCreates** [comment]
FYI if maximumAge is not set in your configuration options it caches getCurrentPosition's coordinates for infinity. You have to explicitly set it to 0 or some other number (note there is another bug that has been raised where maximumAge is in _seconds_ not milliseconds.)

However, I'm still seeing cached GPS coords on a real iOS device when calling getCurrentPosition, Android works just fine so I am baffled.

**Comment by Agontuk** [comment]
> FYI if maximumAge is not set in your configuration options it caches getCurrentPosition's coordinates for infinity. You have to explicitly set it to 0 or some other number (note there is another bug that has been raised where maximumAge is in _seconds_ not milliseconds.)
> 
> However, I'm still seeing cached GPS coords on a real iOS device when calling getCurrentPosition, Android works just fine so I am baffled.

The default value for `maximumAge` is `Infinity`. But according to [mozilla web spec](https://developer.mozilla.org/en-US/docs/Web/API/PositionOptions), it should be `0` by default. I'll probably update it in the next beta version.

I'm still not sure what causes the cached behavior as you described. I don't have any ios devices, so it's hard to debug the issue.

**Comment by ricardofadini** [comment]
I was having the same issue only on Android devices. I took a look at the code and notice that is using the "getLastLocation" method instead of the "getCurrentLocation" method from the FusedLocationProviderClient.

Please refer to: https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient

We've made an internal patch replacing by the new method and that solved the issue.

PS: We had to update the play-services-location to version 17.1.0.

**Comment by alexfov** [comment]
@ricardofadini how it goes?

**Comment by ricardofadini** [comment]
Sorry @alexfov, I'm not sure I got the question.
Anyways, after the referred update, everything is working fine so far.

**Comment by alexfov** [comment]
@ricardofadini yeah, I meant how it works on your project so far. I did the same. But it now takes about 6 seconds to get a position. Thank you a lot for the hint about update play-services-location, you've made my day.

**Comment by ricardofadini** [comment]
@alexfov, it's slower for me as well, unfortunately. But we didn't detect any side effects besides the increased time to load so far. The update's not live for 100% of our users though (and we do have a few Android 5 users), but I'll update here if anything unexpected happens.

**Comment by slim81** [comment]
We found that version 5.3 of the library was returning cached results often.  After reviewing our logs we noticed a discrepancy in the GPS timestamp when compared to the users device time.  

This wasn't always the case and appeared to be related to an update we did to our application in September of 2021.

We started testing via the simulator (iOS) and we saw cached data being returned.  In our live data (logs), we saw cached data being returned mostly for Android.

Reverted and locked in version to ~5.0.0 appears to fix the issue on the simulator and on a physical device.

**Comment by slim81** [comment]
> We found that version 5.2 of the library was returning cached results often. After reviewing our logs we noticed a discrepancy in the GPS timestamp when compared to the users device time.
> 
> This wasn't always the case and appeared to be related to an update we did to our application in September of 2021.
> 
> We started testing via the simulator (iOS) and we saw cached data being returned. In our live data (logs), we saw cached data being returned mostly for Android.
> 
> Reverted and locked in version to ~5.0.0 appears to fix the issue on the simulator and on a physical device.

Reverting back to 5.0 fixed our issue.  

I then updated to the latest version in hopes of providing some details about the issue so it could be fixed...however I no longer see the issue.  

So take my post as a grain of salt.

**Comment by Agontuk** [comment]
`v5.3.0-beta.4` released, please check if it solves the issue on iOS.

**Comment by Agontuk** [comment]
For android, try updating play services location version to 18.0.0. Hopefully it'll solve the issue.

[https://developers.google.com/android/guides/releases#february_18_2021](https://developers.google.com/android/guides/releases#february_18_2021)

**Comment by buptyyf** [comment]
> > Can you check if this happens on a real device too ? Also is it only ios specific ?
> 
> I confirm that it happens on real device. When getCurrentPosition, it got cached location without update latest location, but if we open GoogleMap, then getCurrentPosition, it return newest location. So how we can update the location to latest before getCurrentPosition ?

I have the same question, but I still don't know how to solve it. Have you solved that?

**Comment by c-info** [comment]
Having the same issue on Android phone returning the cached location 

having below configuration 

{
        accuracy: {
          android: 'balanced',
          ios: 'best',
        },
        enableHighAccuracy: true,
        distanceFilter: 20,
        interval: 10000,
        fastestInterval: 5000,
        showLocationDialog: false,
        forceRequestLocation: true,
        forceLocationManager: true,
      },
