### ISSUE TITLE
First location mostly not accurate on mobile data

### ISSUE THREAD

**Issue by m-ramp** [Agontuk/react-native-geolocation-service#210]
RN: 0.63.2
Platform: Android
react-native-geolocation-service: ^5.0.0

I am using `getCurrentPosition` to get user's current fresh accurate position every couple of minutes.

This happens only in certain places. Since I am on mobile data, most of the time first location is not accurate

![WhatsApp Image 2020-10-05 at 9 54 09 PM](https://user-images.githubusercontent.com/4856999/95193390-5fc21600-07f1-11eb-9f0b-7c1e43b6721c.jpeg)

However, if I use `watchPosition` to get location continuously, location gradually becomes accurate after gps is set.

![WhatsApp Image 2020-10-06 at 4 01 58 PM](https://user-images.githubusercontent.com/4856999/95193948-39e94100-07f2-11eb-9356-fa5d21e6b5c9.jpeg)
![WhatsApp Image 2020-10-06 at 4 09 00 PM](https://user-images.githubusercontent.com/4856999/95193963-453c6c80-07f2-11eb-8742-bb2cfac1153c.jpeg)

 What I want is to get only one single location that is accurate (~20m).
Modified ` onLocationResult` in `SingleLocationUpdate.java` and it seems to do what I want.

    public void onLocationResult(LocationResult locationResult) {
      synchronized (SingleLocationUpdate.this) {
        Location location = locationResult.getLastLocation();

        float accuracy = location.getAccuracy();

        if(accuracy < 50){ //configurable desired accuracy
          invokeSuccess(LocationUtils.locationToMap(location));

          mHandler.removeCallbacks(mTimeoutRunnable);

        // Remove further location update.
        if (mFusedProviderClient != null && mLocationCallback != null) {
          mFusedProviderClient.removeLocationUpdates(mLocationCallback);
        }

        }
        else{
          //continue until max attempts
        }
         
      }
    }

Any better way to do this?

**Comment by Agontuk** [comment]
There's no guarantee that you'll get accurate location in your first try. The code you posted is basically same as handling it in app using watch position. The best you can do is to filter out the inaccurate results. Sadly I don't know if there's any way to achieve what you're describing. Just to be sure, did you set `enableHighAccuracy: true` ?

**Comment by m-ramp** [comment]
Yes.
I had `enableHighAccuracy: true` and `maximumAge:0` since I wanted an accurate fresh position.

**Comment by Mprogrammer2020** [comment]
Hi @m-ramp, have you got the solution?

**Comment by m-ramp** [comment]
Not a direct solution, as per [comment](https://github.com/Agontuk/react-native-geolocation-service/issues/210#issuecomment-706672856 ), we will have to filter out inaccurate results until we get an accurate one.
Or you can use my [fork]https://github.com/m-ramp/react-native-geolocation-service/commit/fa51e67d88a6f961a34b1586eb6e8790334758e4) as base where I have this handled.
