### ISSUE TITLE
Location permission request not coming both iOS and Android

### ISSUE THREAD

**Issue by raazatul7** [Agontuk/react-native-geolocation-service#211]
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 50.46 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

using : **react-native-geolocation-service: "^5.0.0"**

Not able to get permission popup. It won't as for permission.

```
  componentDidMount = () => {
    Geolocation.getCurrentPosition(
      (info) => {
        let lat = info.coords.latitude;
        let lng = info.coords.longitude;
        this.getLocation(lat, lng);
      },
      (err) => {
        console.log('location err=>', err);
        alert('Location error');
      },
    );
  };
```

**Comment by Agontuk** [comment]
Give a sample code how you're requesting permission.

**Comment by raazatul7** [comment]
> Give a sample code how you're requesting permission.

`  componentDidMount = () => {
    Geolocation.getCurrentPosition(
      (info) => {
        let lat = info.coords.latitude;
        let lng = info.coords.longitude;
        this.getLocation(lat, lng);
      },
      (err) => {
        console.log('location err=>', err);
        alert('Loation error');
      },
    );
  };`

**Comment by Agontuk** [comment]
You're requesting location, not permission. Check the `requestAuthorization` method for iOS from this library and `PermissionAndroid` for android from react-native.

**Comment by cmcodes-uniworks** [comment]
@Agontuk I am using the following function to request permission and later calling it inside `useEffect()` before `Geolocation.getCurrentPosition()`. Getting no error and no location. Am I doing anything wrong? Can you share any working example?

```jsx
  async function requestPermissions() {
    if (Platform.OS === 'ios') {
      Geolocation.requestAuthorization();
      Geolocation.setRNConfiguration({
        skipPermissionRequests: false,
        authorizationLevel: 'whenInUse',
      });
    }
    if (Platform.OS === 'android') {
      await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION,
      );
    }
  }
```

```jsx
useEffect(() => {
    requestPermissions();
    Geolocation.getCurrentPosition(
      position => { console.log("POS" + position); // not logging anything 
         setlatitude(position.coords.latitude);
         setlongitude(position.coords.longitude); },
      error => { Alert.alert(error.message.toString()); }, // no error displayed
      { showLocationDialog: true, enableHighAccuracy: true, timeout: 15000, maximumAge: 10000 }
    );
  });
```

Also modified `build.gradle` & `AndroidManifest.xml` just like you mentioned in the docs.

**Comment by Agontuk** [comment]
> @Agontuk I am using the following function to request permission and later calling it inside `useEffect()` before `Geolocation.getCurrentPosition()`. Getting no error and no location. Am I doing anything wrong? Can you share any working example?

Why are you using `useEffect` for this ? `useEffect` will be called every time after render, so not a good place to use this. Also `setRNConfiguration` is deprecated in recent versions and `requestAuthorization` method needs an argument. Please check the documentation.
