### ISSUE TITLE
null is not an object (evaluating 'RNFusedLocation.getCurrentPosition')

### ISSUE THREAD

**Issue by sadeh-n** [Agontuk/react-native-geolocation-service#213]
![null is not an object evaluating RNFusedLocation getCurrentPosition](https://user-images.githubusercontent.com/51997297/95985960-22095280-0dda-11eb-8892-69b1e2ac7e54.jpg)

react-native: 0.63.3

"react-native-geolocation-service": "^5.0.0",

       this.setState({ loading: true }, () => {
            Geolocation.getCurrentPosition(
                (position) => {
                     this.setState({  loading: false });
                    console.log(position);
                },
                (error) => {
                     this.setState({ loading: false });
                    console.log(error);
                },
            );
        });
    };

**Comment by Agontuk** [comment]
Make sure your setup is ok, this only happens if native module is not linked properly.
