### ISSUE TITLE
getCurrentPosition slow if Precise Location is set to Off on iOS 14

### ISSUE THREAD

**Issue by alexandersandberg** [Agontuk/react-native-geolocation-service#214]
If Precise Location is set to Off in settings, `getCurrentPosition()` takes from my testing ~10 seconds to resolve the location.

Happens irregardless of what `enableHighAccuracy` is set to.

Tested on both simulator and physical device with the same results. Using the master branch.

**Comment by Agontuk** [comment]
iOS 14 has added some new functionalities in location. Probably need to expose precise location related options/method from this library. I'll take a look as soon as I can.

**Comment by richardli123** [comment]
Thank you Agontuk for creating this package. It has helped me alot as I was using the old geolocation package. Is there any update on this issue as I am also running into it

**Comment by JeffAbney** [comment]
@alexandersandberg where exactly is the Precise Location setting you mention? Inside the app's settings or general phone settings?

**Comment by alexandersandberg** [comment]
@JeffAbney This is a new iOS 14 Location Services option for each app, found in device settings.

You can find it by going to one of the following:
- Settings > {Your App} > Location
- Privacy > Location Services > {Your App}

![IMG_46C6204982C9-1](https://user-images.githubusercontent.com/35671299/100068696-25abe280-2e38-11eb-82cf-f125117b0af9.jpeg)

**Comment by NoahFace** [comment]
The cause of this issue is the following in RNFusedLocation.swift: 

    let locManager = CLLocationManager()
    locManager.delegate = self
    locManager.desiredAccuracy = getAccuracy(options)
    locManager.distanceFilter = distanceFilter
    locManager.startUpdatingLocation() //<<<<<<<<<<<<< requestLocation()

If you change requestLocation() to startUpdatingLocation(), IOS location services will start returning location values immediately rather than after 10 seconds. I don't know the code well enough to tell you if this will impact subscriptions,
but if you just want one-off location reads this will fix the issue.

**Comment by JBuijgers** [comment]
Am I correct that this one is fixed after https://github.com/Agontuk/react-native-geolocation-service/commit/4a9b6ce5eb2101333d0a69e9b344060419b99af2 is released? If so, @Agontuk any plans for a new release? :-)

**Comment by Agontuk** [comment]
v5.2.0 has been published with location delay fix.
