### ISSUE TITLE
watchPosition not working properly [React hooks]

### ISSUE THREAD

**Issue by govind1530** [Agontuk/react-native-geolocation-service#215]
its not give accurate  latitude and longitude...... and when mobile is not moving its changing heading. (both ios and android)

    react-native-geolocation-service: "^5.0.0
    react": "16.13.1",
    react-native": "0.63.2",

`useEffect(() => {

    const watchId = Geolocation.watchPosition(
      (pos) => {
        console.log('live traking', pos);
      },
      (e) => console.log('watch poistion error', e),
      {
        enableHighAccuracy: true,
        timeout: 15000,
        maximumAge: 1000,
        distanceFilter: 0,
       },
    );
    return () => Geolocation.clearWatch(watchId);
  }, []);`

**Comment by Agontuk** [comment]
This is not related to react hooks. And this is expected, location/heading is not exact. It'll vary depending on device & gps.
