### ISSUE TITLE
not building in IOS

### ISSUE THREAD

**Issue by lucasapereira** [Agontuk/react-native-geolocation-service#220]
It is running fine in windows with android, but when I try to run on ios it gives me this error:

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1
PrecompileSwiftBridgingHeader normal x86_64

react native 0.60.5

any ideas?

**Comment by lucasapereira** [comment]
In file included from /Users/runner/work/1/s/node_modules/rn-fetch-blob/ios/RNFetchBlobFS.m:10:
  "value witness table for Builtin.Int32", referenced from:
      full type metadata for __C.CLError in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "protocol descriptor for Swift.Error", referenced from:
      _got.$ss5ErrorMp in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "(extension in Swift):Swift.Error._userInfo.getter : Swift.AnyObject?", referenced from:
      protocol witness for Swift.Error._userInfo.getter : Swift.AnyObject? in conformance __C_Synthesized.related decl 'e' for CLError : Swift.Error in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_react_native_geolocation_service)
  "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
      __swift_FORCE_LOAD_$_swiftDarwin_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_react_native_geolocation_service)
  "protocol descriptor for Swift.Hashable", referenced from:
      _got.$sSHMp in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "nominal type descriptor for Swift._DictionaryStorage", referenced from:
      _got.$ss18_DictionaryStorageCMn in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_react_native_geolocation_service)
  "__swift_FORCE_LOAD_$_swiftFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftFoundation_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFoundation_$_react_native_geolocation_service)
  "__swift_FORCE_LOAD_$_swiftCoreLocation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreLocation_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreLocation_$_react_native_geolocation_service)
  "_swift_deletedMethodError", referenced from:
      type metadata for react_native_geolocation_service.RNFusedLocation in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "Swift._bridgeAnythingToObjectiveC<A>(A) -> Swift.AnyObject", referenced from:
      partial apply forwarder for reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> () to @escaping @callee_guaranteed (@in_guaranteed Any?) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_getObjCClassMetadata", referenced from:
      type metadata accessor for __C.OS_dispatch_queue in libreact-native-geolocation-service.a(RNFusedLocation.o)
      merged type metadata accessor for __C.CLLocation in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_release_n", referenced from:
      function signature specialization <Arg[1] = Dead> of react_native_geolocation_service.RNFusedLocation.timerFired(timer: __C.NSTimer) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "protocol descriptor for Swift.RawRepresentable", referenced from:
      _got.$sSYMp in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftCompatibility50", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility50_$_react_native_geolocation_service)
  "Foundation.Date.init() -> Foundation.Date", referenced from:
      react_native_geolocation_service.RNFusedLocation.getCurrentPosition(_: [Swift.String : Any], successCallback: ([Any]?) -> (), errorCallback: ([Any]?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "method descriptor for Swift.Error._domain.getter : Swift.String", referenced from:
      _got.$ss5ErrorP7_domainSSvgTq in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_deallocObject", referenced from:
      l_objectdestroy in libreact-native-geolocation-service.a(RNFusedLocation.o)
      l_objectdestroy.2 in libreact-native-geolocation-service.a(RNFusedLocation.o)
      l_objectdestroy.12 in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_unknownObjectRetain_n", referenced from:
      function signature specialization <Arg[2] = Dead> of react_native_geolocation_service.RNFusedLocation.(generateErrorResponse in _45344B17DFC39716C010A486DA74C10D)(code: Swift.Int, message: Swift.String) -> [Swift.String : Any] in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftUIKit", referenced from:
      __swift_FORCE_LOAD_$_swiftUIKit_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftUIKit_$_react_native_geolocation_service)
  "(extension in Foundation):Foundation._BridgedStoredNSError._getEmbeddedNSError() -> Swift.AnyObject?", referenced from:
      protocol witness for Swift.Error._getEmbeddedNSError() -> Swift.AnyObject? in conformance __C_Synthesized.related decl 'e' for CLError : Swift.Error in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "(extension in Foundation):Swift.String._bridgeToObjectiveC() -> __C.NSString", referenced from:
      react_native_geolocation_service.RNFusedLocation.startLocationUpdate([Swift.String : Any]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didFailWithError: Swift.Error) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_setDeallocating", referenced from:
      react_native_geolocation_service.RNFusedLocation.getCurrentPosition(_: [Swift.String : Any], successCallback: ([Any]?) -> (), errorCallback: ([Any]?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      function signature specialization <Arg[2] = Dead> of react_native_geolocation_service.RNFusedLocation.(generateErrorResponse in _45344B17DFC39716C010A486DA74C10D)(code: Swift.Int, message: Swift.String) -> [Swift.String : Any] in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "Swift._CocoaArrayWrapper.subscript.getter : (Swift.Int) -> Swift.AnyObject", referenced from:
      generic specialization <__C.CLLocation> of Swift._ArrayBuffer._getElementSlowPath(Swift.Int) -> Swift.AnyObject in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "method descriptor for Swift.Hashable.hash(into: inout Swift.Hasher) -> ()", referenced from:
      _got.$sSH4hash4intoys6HasherVz_tFTq in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "static (extension in Dispatch):__C.OS_dispatch_queue.main.getter : __C.OS_dispatch_queue", referenced from:
      @objc react_native_geolocation_service.RNFusedLocation.methodQueue.getter : __C.OS_dispatch_queue in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "Swift.Hasher.init(_seed: Swift.Int) -> Swift.Hasher", referenced from:
      protocol witness for Swift.Hashable._rawHashValue(seed: Swift.Int) -> Swift.Int in conformance __C_Synthesized.related decl 'e' for CLError : Swift.Hashable in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
      generic specialization <Swift.String> of Swift.__RawDictionaryStorage.find<A where A: Swift.Hashable>(A) -> (bucket: Swift._HashTable.Bucket, found: Swift.Bool) in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "method descriptor for Swift.RawRepresentable.init(rawValue: A.RawValue) -> A?", referenced from:
      _got.$sSY8rawValuexSg03RawB0Qz_tcfCTq in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_deallocClassInstance", referenced from:
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_errorRetain", referenced from:
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didFailWithError: Swift.Error) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "(extension in Foundation):Foundation._BridgedStoredNSError.hash(into: inout Swift.Hasher) -> ()", referenced from:
      protocol witness for Swift.Hashable.hash(into: inout Swift.Hasher) -> () in conformance __C_Synthesized.related decl 'e' for CLError : Swift.Hashable in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
      protocol witness for Swift.Hashable._rawHashValue(seed: Swift.Int) -> Swift.Int in conformance __C_Synthesized.related decl 'e' for CLError : Swift.Hashable in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "associated conformance descriptor for Foundation._BridgedStoredNSError.Foundation._BridgedStoredNSError.Code.Swift.RawRepresentable.RawValue: Swift.FixedWidthInteger", referenced from:
      _got.$s10Foundation21_BridgedStoredNSErrorP4CodeAC_8RawValueSYs17FixedWidthIntegerTn in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_getForeignTypeMetadata", referenced from:
      merged type metadata accessor for __C_Synthesized.related decl 'e' for CLError in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "nominal type descriptor for Swift._ContiguousArrayStorage", referenced from:
      _got.$ss23_ContiguousArrayStorageCMn in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityDynamicReplacements_$_react_native_geolocation_service)
  "static (extension in Foundation):Foundation._BridgedStoredNSError.== infix(A, A) -> Swift.Bool", referenced from:
      protocol witness for static Swift.Equatable.== infix(A, A) -> Swift.Bool in conformance __C_Synthesized.related decl 'e' for CLError : Swift.Equatable in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
      __swift_FORCE_LOAD_$_swiftDispatch_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_react_native_geolocation_service)
  "(extension in Foundation):Swift.Error< where A: Foundation.CustomNSError>._domain.getter : Swift.String", referenced from:
      protocol witness for Swift.Error._domain.getter : Swift.String in conformance __C_Synthesized.related decl 'e' for CLError : Swift.Error in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "(extension in Foundation):Foundation._BridgedStoredNSError.init(_bridgedNSError: __C.NSError) -> A?", referenced from:
      protocol witness for Foundation._ObjectiveCBridgeableError.init(_bridgedNSError: __shared __C.NSError) -> A? in conformance __C_Synthesized.related decl 'e' for CLError : Foundation._ObjectiveCBridgeableError in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftCompatibility51", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility51_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility51_$_react_native_geolocation_service)
  "(extension in ObjectiveC):__C.NSObject.hashValue.getter : Swift.Int", referenced from:
      protocol witness for Swift.Hashable.hashValue.getter : Swift.Int in conformance __C_Synthesized.related decl 'e' for CLError : Swift.Hashable in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_getInitializedObjCClass", referenced from:
      react_native_geolocation_service.RNFusedLocation.getCurrentPosition(_: [Swift.String : Any], successCallback: ([Any]?) -> (), errorCallback: ([Any]?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.startLocationUpdate([Swift.String : Any]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      type metadata accessor for react_native_geolocation_service.RNFusedLocation in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didFailWithError: Swift.Error) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      generic specialization <__C.CLLocation> of Swift._ArrayBuffer._getElementSlowPath(Swift.Int) -> Swift.AnyObject in libreact-native-geolocation-service.a(RNFusedLocation.o)
      function signature specialization <Arg[2] = Dead> of react_native_geolocation_service.RNFusedLocation.requestAuthorization(_: Swift.String, resolve: (Any?) -> (), reject: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      merged type metadata accessor for __C.CLLocation in libreact-native-geolocation-service.a(RNFusedLocation.o)
      ...
  "method descriptor for Foundation._BridgedStoredNSError._nsError.getter : __C.NSError", referenced from:
      _got.$s10Foundation21_BridgedStoredNSErrorP8_nsErrorSo0D0CvgTq in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "(extension in Foundation):Foundation._BridgedStoredNSError.errorUserInfo.getter : [Swift.String : Any]", referenced from:
      protocol witness for Foundation.CustomNSError.errorUserInfo.getter : [Swift.String : Any] in conformance __C_Synthesized.related decl 'e' for CLError : Foundation.CustomNSError in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "static (extension in Foundation):Swift.Dictionary._unconditionallyBridgeFromObjectiveC(__C.NSDictionary?) -> [A : B]", referenced from:
      @objc react_native_geolocation_service.RNFusedLocation.getCurrentPosition(_: [Swift.String : Any], successCallback: ([Any]?) -> (), errorCallback: ([Any]?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      @objc react_native_geolocation_service.RNFusedLocation.startLocationUpdate([Swift.String : Any]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "(extension in Foundation):Foundation._BridgedStoredNSError.errorCode.getter : Swift.Int", referenced from:
      protocol witness for Foundation.CustomNSError.errorCode.getter : Swift.Int in conformance __C_Synthesized.related decl 'e' for CLError : Foundation.CustomNSError in __C_Synthesized in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftCoreImage", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreImage_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreImage_$_react_native_geolocation_service)
  "(extension in Foundation):Foundation._BridgedStoredNSError.code.getter : A.Code", referenced from:
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didFailWithError: Swift.Error) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "Foundation.Date.timeIntervalSince1970.getter : Swift.Double", referenced from:
      react_native_geolocation_service.RNFusedLocation.getCurrentPosition(_: [Swift.String : Any], successCallback: ([Any]?) -> (), errorCallback: ([Any]?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "static (extension in Foundation):Swift.Array._unconditionallyBridgeFromObjectiveC(__C.NSArray?) -> [A]", referenced from:
      @objc react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_bridgeObjectRetain", referenced from:
      react_native_geolocation_service.RNFusedLocation.getCurrentPosition(_: [Swift.String : Any], successCallback: ([Any]?) -> (), errorCallback: ([Any]?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.startLocationUpdate([Swift.String : Any]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      generic specialization <__C.CLLocation> of Swift._ArrayBuffer._getElementSlowPath(Swift.Int) -> Swift.AnyObject in libreact-native-geolocation-service.a(RNFusedLocation.o)
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of generic specialization <Swift.String, Any> of Swift.Dictionary.init(dictionaryLiteral: (A, B)...) -> [A : B] in libreact-native-geolocation-service.a(RNFusedLocation.o)
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of generic specialization <Swift.String, Swift.String> of Swift.Dictionary.init(dictionaryLiteral: (A, B)...) -> [A : B] in libreact-native-geolocation-service.a(RNFusedLocation.o)
      function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Dead> of generic specialization <Swift.String, Swift.Double> of Swift.Dictionary.init(dictionaryLiteral: (A, B)...) -> [A : B] in libreact-native-geolocation-service.a(RNFusedLocation.o)
      ...
  "method descriptor for Foundation.CustomNSError.errorCode.getter : Swift.Int", referenced from:
      _got.$s10Foundation13CustomNSErrorP9errorCodeSivgTq in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "base conformance descriptor for Foundation._BridgedStoredNSError: Swift.Hashable", referenced from:
      _got.$s10Foundation21_BridgedStoredNSErrorPSHTb in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
      __swift_FORCE_LOAD_$_swiftMetal_$_react_native_geolocation_service in libreact-native-geolocation-service.a(RNFusedLocation.o)
     (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_react_native_geolocation_service)
  "static Foundation.Date._unconditionallyBridgeFromObjectiveC(__C.NSDate?) -> Foundation.Date", referenced from:
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "method descriptor for Foundation.CustomNSError.errorUserInfo.getter : [Swift.String : Any]", referenced from:
      _got.$s10Foundation13CustomNSErrorP13errorUserInfoSDySSypGvgTq in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "Swift._CocoaArrayWrapper.endIndex.getter : Swift.Int", referenced from:
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "method descriptor for static Swift.Equatable.== infix(A, A) -> Swift.Bool", referenced from:
      _got.$sSQ2eeoiySbx_xtFZTq in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "_swift_getTypeByMangledNameInContext", referenced from:
      ___swift_instantiateConcreteTypeFromMangledName in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "(extension in Foundation):Swift.Array._bridgeToObjectiveC() -> __C.NSArray", referenced from:
      @objc react_native_geolocation_service.RNFusedLocation.supportedEvents() -> [Swift.String]? in libreact-native-geolocation-service.a(RNFusedLocation.o)
      partial apply forwarder for reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned __C.NSArray?) -> () to @escaping @callee_guaranteed (@guaranteed [Any]?) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "Swift._stringCompareWithSmolCheck(_: Swift._StringGuts, _: Swift._StringGuts, expecting: Swift._StringComparisonResult) -> Swift.Bool", referenced from:
      react_native_geolocation_service.RNFusedLocation.startLocationUpdate([Swift.String : Any]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      generic specialization <Swift.String> of Swift.__RawDictionaryStorage.find<A where A: Swift.Hashable>(_: A, hashValue: Swift.Int) -> (bucket: Swift._HashTable.Bucket, found: Swift.Bool) in libreact-native-geolocation-service.a(RNFusedLocation.o)
      function signature specialization <Arg[2] = Dead> of react_native_geolocation_service.RNFusedLocation.requestAuthorization(_: Swift.String, resolve: (Any?) -> (), reject: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      function signature specialization <Arg[1] = Dead> of react_native_geolocation_service.RNFusedLocation.(getAccuracy in _45344B17DFC39716C010A486DA74C10D)([Swift.String : Any]) -> Swift.Double in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "Swift._bridgeAnyObjectToAny(Swift.AnyObject?) -> Any", referenced from:
      react_native_geolocation_service.RNFusedLocation.startLocationUpdate([Swift.String : Any]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      function signature specialization <Arg[1] = Dead> of react_native_geolocation_service.RNFusedLocation.timerFired(timer: __C.NSTimer) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "method descriptor for static Foundation.CustomNSError.errorDomain.getter : Swift.String", referenced from:
      _got.$s10Foundation13CustomNSErrorP11errorDomainSSvgZTq in libreact-native-geolocation-service.a(RNFusedLocation.o)
  "(extension in Foundation):Swift.Dictionary._bridgeToObjectiveC() -> __C.NSDictionary", referenced from:
      react_native_geolocation_service.RNFusedLocation.getCurrentPosition(_: [Swift.String : Any], successCallback: ([Any]?) -> (), errorCallback: ([Any]?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didFailWithError: Swift.Error) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)

** ARCHIVE FAILED **

**Comment by lucasapereira** [comment]
Any ideas?

**Comment by devleonardorabelo** [comment]
I'm having the same problem :(

**Comment by celciusjj** [comment]
Mismo problema

**Comment by rahombus97** [comment]
Same problem also.

**Comment by himanshi7046** [comment]
https://github.com/Agontuk/react-native-geolocation-service/blob/master/docs/setup.md

Read all step for ios build

**Comment by shubhambathe1** [comment]
Working fine on android, but build is failing while  running on iOS simulator. Here is the error message:-

* BUILD FAILED *

The following build commands failed:
	CompileSwift normal x86_64 /Users/webwerks/Desktop/Shubham/KM/pnp2-rn-app/node_modules/react-native-geolocation-service/ios/RNFusedLocation.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by Agontuk** [comment]
Make sure you setup a dummy swift file & bridging header as mentioned in the docs. It looks like xcode is unable to compile swift file.

**Comment by shubhambathe1** [comment]
@Agontuk I had followed all the steps in the setup document, which included added a dummy swift file and bridging header as well. Still its not working. Just a side note I have added use_native_modules! in my Pod file due to some project dependencies. Could it be the reason for these build errors?

**Comment by Agontuk** [comment]
As far as I know `use_native_modules!` is already there in the podfile by default, so I don't think it's the main issue.

**Comment by Agontuk** [comment]
Try the example project, see if this works. It's not a library issue as far as I know since others are using it without any build errors. Just to be sure, are you creating the dummy swift file via xcode or other editor ?

**Comment by shubhambathe1** [comment]
Yes I am using Xcode only to create the dummy swift file. Also it gave the option to link headers. Will try to run the example tomorrow.

**Comment by shubhambathe1** [comment]
@Agontuk I cloned the repo and tried to run the example project on iOS through command line. But its still giving same build errors. Then I tried to run the project through xcode. There I am getting the error as follows:-

Use of unresolved identifier 'kCLLocationAccuracyReduced'
 
<img width="1277" alt="Screenshot at Feb 19 18-04-12" src="https://user-images.githubusercontent.com/31159892/108506452-cea29600-72de-11eb-9410-f6ffc01db7bd.png">

Same issue is also opened by someone. Here is the link:-
[https://github.com/Agontuk/react-native-geolocation-service/issues/241](url)

Please debug this issue and let us know if its fixable any time soon.

Thanks & Regards.

**Comment by Agontuk** [comment]
You need to have xcode 12  to fix this issue, there's no other way around. This was introduced in ios 14.

**Comment by shubhambathe1** [comment]
@Agontuk After updating xcode to lastest version 12.4 it started working fine. Thanks for helping me out. It was neither the library issue nor my project issue, but xcode and iOS 14 issue.

**Comment by Agontuk** [comment]
I think updating the xcode will solve this issue for other devs too. So closing this for now, feel free to open a new issue if problem persists.

**Comment by chenop** [comment]
Xcode 12.4
react-native-geolocation-service: 5.2.0

Still got the same issue (I think):

      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didChangeAuthorization: __C.CLAuthorizationStatus) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      outlined copy of @escaping @callee_guaranteed @substituted <A, B> (@in_guaranteed A) -> (@out B) for <Any?()>? in libreact-native-geolocation-service.a(RNFusedLocation.o)
      outlined copy of @escaping @callee_guaranteed @substituted <A, B> (@in_guaranteed A) -> (@out B) for <[Any]?()>? in libreact-native-geolocation-service.a(RNFusedLocation.o)
      outlined copy of @escaping @callee_guaranteed (@guaranteed [Any]?) -> ()? in libreact-native-geolocation-service.a(RNFusedLocation.o)
      ...
  "_swift_unknownObjectRelease", referenced from:
      react_native_geolocation_service.RNFusedLocation.init() -> react_native_geolocation_service.RNFusedLocation in libreact-native-geolocation-service.a(RNFusedLocation.o)
      reabstraction thunk helper from @escaping @callee_unowned @convention(block) (@unowned Swift.AnyObject?) -> () to @escaping @callee_guaranteed (@in_guaranteed Any?) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.getCurrentPosition(_: [Swift.String : Any], successCallback: ([Any]?) -> (), errorCallback: ([Any]?) -> ()) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.timerFired(timer: __C.NSTimer) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.(checkPlistKeys in _45344B17DFC39716C010A486DA74C10D)(authorizationLevel: Swift.String) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.(shouldAllowBackgroundUpdate in _45344B17DFC39716C010A486DA74C10D)() -> Swift.Bool in libreact-native-geolocation-service.a(RNFusedLocation.o)
      react_native_geolocation_service.RNFusedLocation.locationManager(_: __C.CLLocationManager, didUpdateLocations: [__C.CLLocation]) -> () in libreact-native-geolocation-service.a(RNFusedLocation.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by gpsugy** [comment]
Looks like this issue occurs from versions 5.0.0 and up. Downgrade to 4.0.2 and it should work as a temporary solution. I currently use Xcode 12.4 with React Native 0.60.5

**Comment by Parth15Ordex** [comment]
@Agontuk 
I am using **Xcode 12.4** and also using latest version of **react-native-geolocation-service (^5.3.0-beta.1)**.
Also I have followed exact steps which are mentioned in documentation.

### While building iOS I am getting below error
        The following build commands failed:
        CompileSwift normal x86_64
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
        CompileSwift normal arm64
        CompileSwift normal x86_64 /Users/parth/Desktop/Demo/demomobile/Demo/node_modules/react-native-geolocation-service/ios/RNFusedLocation.swift

 And I got stuck here while building iOS.

Can you help me here to get out of this?
