### ISSUE TITLE
Google map is loading whole the time

### ISSUE THREAD

**Issue by Mertez** [Agontuk/react-native-geolocation-service#221]
The top section which shows the google map is always empty with google sign
I tried to change Style and then I saw an indicator inside google map which was hidden until that time.
But no map on google map :(

**Comment by Agontuk** [comment]
If you're talking about the example project, you need to provide a map api key in `AndroidManifest.xml` file.

**Comment by Agontuk** [comment]
Closing this, as the above comment should solve your issue.
