### ISSUE TITLE
iOS `getCurrentPosition` can only handle 1 request at a time

### ISSUE THREAD

**Issue by cjpete** [Agontuk/react-native-geolocation-service#225]
This is not normally an issue because the requests are served so quickly, but when considered with #214 it is problematic.

E.g:
```
09:38:27.571	client_log	**** [appState active]
09:38:27.912	client_log	**** location check start (id1)
09:38:28.960	client_log	**** [appState inactive]
09:38:30.237	client_log	**** [appState background]
09:38:31.336	client_log	**** [appState active]
09:38:31.433	client_log	**** location check start (id2)
09:38:37.920	client_log	**** location check error (id2) {"code": 2, "message": "The operation couldn’t be completed"}
09:38:47.918	client_log	**** location check error (id1) {"code": 3, "message": "Location request timed out"}
```

I assume what is happening is that the `errorCallback` and `successCallback` for the second request overwrite that of the first, meaning that the error from the first request gets reported to the callbacks for the second request, and then the timeout for the first request fails because it's callbacks were not triggered.

**Comment by Agontuk** [comment]
Yes, this is right now a problem. We should probably maintain a list of pending requests and resolve all of them when we get a location fix or an error.

**Comment by Agontuk** [comment]
This should be working in the latest version, so closing this.
