### ISSUE TITLE
Feature request: iOS specifically ask for precise or non-precise location

### ISSUE THREAD

**Issue by helloagain-dev** [Agontuk/react-native-geolocation-service#228]
As far as I can see, the `enableHighAccuracy` prop, has no effect on the precise location, since in both cases `enabledHighAccuracy` results in either:

- kCLLocationAccuracyBest
- kCLLocationAccuracyHundredMeters

which both require precise location.

Since Apple now introduced a new App Privacy section, it would be good to be able to choose in `getCurrentPosition` if the app should only ask for precise or not precise location, in order to keep the permission to ask for to a minimum.

**Comment by Agontuk** [comment]
A new property `accuracy` is introduced in the recent version. I'll also add support for `reduced` value which will use `kCLLocationAccuracyReduced .`

**Comment by Agontuk** [comment]
v5.2.0 has been published with `reduced` as an accuracy option.
