### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by dlimx** [Agontuk/react-native-geolocation-service#23]
Hello,

I'm getting the following error on build:
```class file for com.google.android.gms.common.internal.safeparcel.zza not found```.

My `build.gradle` has:
```
compile project(':react-native-geolocation-service') {
    exclude group: 'com.google.android.gms', module: 'play-services-location'
}
...
compile 'com.google.android.gms:play-services-location:11.+'
```

Thank you!

**Comment by oakis** [comment]
I don´t think "11.+" is a version.
Try with this:
`compile 'com.google.android.gms:play-services-location:11.8.0'`

**Comment by Agontuk** [comment]
As stated above, you've to provide a specific version. And make sure all other play service libraries are using the same version. Closing this, feel free to ask again if it doesn't work.

**Comment by Agontuk** [comment]
You have to override all other play service libraries to the same version. Look for other libraries that has dependency on play service and override them.

I think variable dependencies in gradle requires gradle 3 support, RN is still using gradle 2.3.
