### ISSUE TITLE
IOS pod install

### ISSUE THREAD

**Issue by emurigar** [Agontuk/react-native-geolocation-service#237]
When I do the 'pod install' I got the following error. I got the version 5.1.1
`The Swift pod `react-native-geolocation-service` depends upon `React-Core`, `React-RCTAnimation`, `React-RCTBlob`, `React-RCTImage`, `React-RCTLinking`, `React-RCTNetwork`, `React-RCTSettings`, `React-RCTText`, `React-RCTVibration`, `Folly`, `React-cxxreact`, `React-jsi`, `React-jsiexecutor`, `glog`, `React-jsinspector`, `RCTTypeSafety`, `ReactCommon`, `FBReactNativeSpec`, and `DoubleConversion`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.`

**Comment by Agontuk** [comment]
This was an issue in 5.1.0, it got fixed in 5.1.1. Try reinstalling the library.

**Comment by Agontuk** [comment]
Closing this since the fix is already available in new versions. Feel free to open a new issue if problem persists
