### ISSUE TITLE
Google Play Console Rejects the app indicating background geolocation use

### ISSUE THREAD

**Issue by fcataldi** [Agontuk/react-native-geolocation-service#240]
My app don't use backgroud geolocation feature, but i received this message from Play Console:]

"We detected that your app contains at least one feature that requests access to location in the background, however  your permission declaration form did not reflect this"

I added the line bellow on my AndroidManifest file, but I'm receiving the same messagem above.

uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" tools:node="remove"

Could you help me please?

Thanks

**Comment by Agontuk** [comment]
This library does not provide any background location feature by default. Check other dependencies and your source code to see if there's any unwanted permissions. It would've been better if there's a detailed explanation from play console.

**Comment by fcataldi** [comment]
There's no problem.
Thank you for the support.

**Comment by msvargas** [comment]
Hi @fcataldi, Can you help me? I have the same problem, what did you do to solve this? 

@Agontuk Please see this google review, I only need foreground location:

Thanks!

![image](https://user-images.githubusercontent.com/8255332/109645840-639a6000-7b25-11eb-9bf3-0d9e28c8b2e9.png)

**Comment by fcataldi** [comment]
Hi @msvargas 
Some time ago, I uploaded to the PlayStore a opened test version.
At this moment, I used 0.59 RN version. Now, I use 0.61 version.
The PlayStore acused this older version and not the new version.
I removed the older version and the new version was accepted.

**Comment by msvargas** [comment]
@fcataldi Thanks, I will try

**Comment by benndip** [comment]
> Hi @msvargas
> Some time ago, I uploaded to the PlayStore a opened test version.
> At this moment, I used 0.59 RN version. Now, I use 0.61 version.
> The PlayStore acused this older version and not the new version.
> I removed the older version and the new version was accepted.

@fcataldi please how can I remove an old version from the playstore console ? as it stands, it looks like it's not possible on the new console.

**Comment by fcataldi** [comment]
> > Hi @msvargas
> > Some time ago, I uploaded to the PlayStore a opened test version.
> > At this moment, I used 0.59 RN version. Now, I use 0.61 version.
> > The PlayStore acused this older version and not the new version.
> > I removed the older version and the new version was accepted.
> 
> @fcataldi please how can I remove an old version from the playstore console ? as it stands, it looks like it's not possible on the new console.

@benndip 
Was a open or closed test version. Probability I turned this version unavailable.
When you receive the alert by Google Play, the packed version is show. Note this. If is not the same version that you are working on, try remove. If is the same version that you are working on, then you have a problem and will be necessary identify the component to be changed.
