### ISSUE TITLE
`getCurrentLocation` not working on IOS without timeout

### ISSUE THREAD

**Issue by chungweileong94** [Agontuk/react-native-geolocation-service#244]
On IOS, if the timeout is not set (default to infinity), the callback will never get called.

I looked into the native code, and I noticed that the recent v5.2.0 changed from `locManager.requestLocation()` to `locManager.startUpdatingLocation()`, which is also the root cause. I tried to revert the change, and everything works fine again.

**Comment by mike-skwi** [comment]
Ran into this same thing today. Noticed when my callback wasn't happening until I added a timeout in the config

**Comment by Agontuk** [comment]
This is pretty weird, I'll take a look.

**Comment by harshvitra** [comment]
Yes I am also facing the same trouble, if I remove the maximumAge it works

**Comment by joaocarmo** [comment]
I've been having the same issue in my project. After reading this issue, adding the `timeout` option with some value fixed it for me.

**Comment by yestay90** [comment]
where you set timeout config ? I am also having problem with callback calling...

**Comment by Agontuk** [comment]
For now, you have to add the timeout option. I'll rewrite the ios implementation soon, will try to address it then.

**Comment by Agontuk** [comment]
`v5.3.0-beta.4` released, please check if it solves this issue.

**Comment by Agontuk** [comment]
Closing this as it should be fixed in latest version
