### ISSUE TITLE
Problem when I try to save coords in Array using useState

### ISSUE THREAD

**Issue by luksrocha** [Agontuk/react-native-geolocation-service#256]
I'm getting the coords and saving it into an array, but, even using spread operator I get only one item into it.

`

    const getLocation = () => {Geolocation.watchPosition(
      (position) => {
        console.log('Array value before save', coords)
        const { latitude, longitude } = position.coords
        setCoords([...coords, latitude + ',' + longitude]);
      },
      (error) => {
        console.log(error);
      },
      {
        fastestInterval: 2500,
        interval: 2500,
        distanceFilter: 1
      })}
  `
and that is what I get

![image](https://user-images.githubusercontent.com/44854940/113191059-7b9ff500-9233-11eb-9256-73c58cc49fdd.png)

I need to save all of coords that I get in my Geolocation.watchPosition(), what should I do?

**Comment by danieltereschenko** [comment]
try to use callback syntax
setCoords(prevState => ([...prevState, `${latitude} ${longitude}`]))

**Comment by luksrocha** [comment]
> try to use callback syntax
> setCoords(prevState => ([...prevState, `${latitude} ${longitude}`]))

It worked for me!! thank you

**Comment by luksrocha** [comment]
> try to use callback syntax
> setCoords(prevState => ([...prevState, `${latitude} ${longitude}`]))

It worked for me!! thank you
