### ISSUE TITLE
Expo RNFusedLocation.getCurrentPosition is null error

### ISSUE THREAD

**Issue by KatancicDenisz** [Agontuk/react-native-geolocation-service#259]
Can I use this package with expo? I tried it and I got an error saying `null is not an object (evaluating RNFusedLocation.getCurrentPosition)`

**Comment by Agontuk** [comment]
Not sure, I didn't try expo yet. I'll check their documentation to see if they support integrating native modules.

**Comment by KatancicDenisz** [comment]
> Not sure, I didn't try expo yet. I'll check their documentation to see if they support integrating native modules.

Okay, thank you.

**Comment by KatancicDenisz** [comment]
> Not sure, I didn't try expo yet. I'll check their documentation to see if they support integrating native modules.

Any luck? :)

**Comment by Agontuk** [comment]
Not able to try it out right now. But as far as I understand, you can't use native dependencies if you're on `Managed Workflow`. It should work fine in `Bare Workflow`.

**Comment by JohnMealy23** [comment]
@Agontuk,

It's been a year, and I'm wondering if things have changed.  

I'm currently getting the error indicated by the OP, but looking at [Expo's docs](https://docs.expo.dev/guides/permissions/#managed-workflow-1), it does look like the managed workflow intends to support `getCurrentPosition` and other location functionality with the proper app.json config.

I'll also follow up on the Expo side to see I can dig anything up there.  Would love some help or indication from this side, too, if possible.  New at React Native and could use all the help I can get!

**Comment by Agontuk** [comment]
I'm pretty sure expo does not support third party native libraries. You can check here [https://docs.expo.dev/workflow/using-libraries/#determining-third-party-library-compatibility](https://docs.expo.dev/workflow/using-libraries/#determining-third-party-library-compatibility)

You need to eject your expo project to install libraries with native code

**Comment by Agontuk** [comment]
Closing this, since it's not possible to add native dependencies in Expo's `Managed Workflow`.

**Comment by elalami-m** [comment]
@Agontuk i got the same issue did you find a solution ??

**Comment by chhornponleu** [comment]
Same issue with Expo 51
