### ISSUE TITLE
[android]: How to turn off 'This app needs location access' popup

### ISSUE THREAD

**Issue by lity-opinov8** [Agontuk/react-native-geolocation-service#261]
At the moment, when initializing the application, I get this popup and at the same time a request to use geolocation in the application, after confirming or refusing to use geolocation, the application is loaded but the popup remains, after pressing OK, again appears a request to use geolocation in the application

react-native 0.64.0
react-native-geolocation-service 5.2.0

![IMG_2705](https://user-images.githubusercontent.com/78354440/115901914-7ae13400-a46a-11eb-8bd8-ec1de7d01f0b.PNG)

**Comment by Agontuk** [comment]
This popup is not part of the library, my guess it's coming from another library. Please check what other libraries you are using.
