### ISSUE TITLE
Geolocation.requestAuthorization() is void in return

### ISSUE THREAD

**Issue by nengliangZ** [Agontuk/react-native-geolocation-service#262]
I am checking the geo permission in iOS by calling Geolocation.requestAuthorization(). From the documentation, it should return status to indicate whether the permission is 'granted', 'denied', or 'disabled'. But the package describes the function will have a void return. 

I am following the example here: https://github.com/Agontuk/react-native-geolocation-service/blob/master/example/src/App.js

Can someone tell what's wrong here? How can I get the iOS permission? Thanks! 

Package version:  "react-native-geolocation-service": "^4.0.2",
iOS: 14.4.2

**Comment by Agontuk** [comment]
You're using  an old version, it's only available in 5.0+ versions.

**Comment by nengliangZ** [comment]
thank you!
