### ISSUE TITLE
Location settings are not satisfied

### ISSUE THREAD

**Issue by reza-mazarlou** [Agontuk/react-native-geolocation-service#28]
I use react-native-geolocation-service for get user current location **without internet** and I  try with your example code , my problem is when WIFI is off app give me thie error : 

`code:5 , Location settings are not satisfied`

and when WIFI is on  app work very well and give me current location

**Comment by Agontuk** [comment]
You mean the message is wrong, or it should've been a different response ?

**Comment by reza-mazarlou** [comment]
I want get user current location **without internet** and send it with SMS , but when WIFI is of this library not work and give me  `Location settings are not satisfied` and when WIFI is on without connect to the any access point this library give me `Time out ` Error , and just worked when WIFI is connected

**Comment by Agontuk** [comment]
I don't think FusedLocationProvider supports getting location without internet. I'll look into the documentation just to be sure.

**Comment by GaneshSaiKumar** [comment]
gives me same error "Location settings are not satisfied." though mobile data wifi are turned on!

**Comment by romreed** [comment]
I got same error 
 "react": "16.7.0",
 "react-native": "^0.58.3",
 "react-native-geolocation-service": "^2.0.0",

**Comment by cladjules** [comment]
Can you try using my PR/Branch,
you can pass a flag "forceRequestLocation: true" that will still try to get a location even though location settings are not satisfied.
You can use it along showLocationDialog: false

https://github.com/Agontuk/react-native-geolocation-service/pull/68

**Comment by romreed** [comment]
@cladjules i will try. thank you.

**Comment by leandroquinger** [comment]
It works for!  
when the device has no wifi connection or it's disabled, it still can get the GPS position.

I just changed the RNFusedLocationModule.java and LocationUtils.java files using the @cladjules  branch and solved the error message "Location settings are not satisfied". It wasn't need to set any flag 

Thanks!

**Comment by vikasrai1502** [comment]
When I put my device on airplane mode and trying to get location getting error message "Location settings are not satisfied". Is react-native-geolocation-service not works in Airplane mode? Please help.

**Comment by hanaechahid** [comment]
@vikasrai1502, yes I think this library not working in airplane mode. I'm trying to search for another library which supports airplane mode but I don't find it.
any library suggestion to resolve this problem?

**Comment by cladjules** [comment]
Now my branch was merged. I think we are halfway from having it working with airplane mode. I will look at doing another PR and some testing when in back from holidays at the end of the month.
But that's definitely doable in that project.

Thanks

**Comment by hanaechahid** [comment]
@cladjules but I need the solution now

**Comment by Agontuk** [comment]
Enabling airplane mode automatically turns off wifi, enable wifi and it should work.

**Comment by entranOA** [comment]
Any updates on this?

**Comment by airtonazevedo** [comment]
@entranOA  I found a very good solution.
I did a project where you can see the solution

https://github.com/airtonazevedo/react-native-geolocation-offline-and-airplanemode

**Comment by saad65** [comment]
If anyone is having this error even with wifi and mobile data turned on, put your location mode in your phone settings to device only and in the findCoordinates function set enableHighAccuracy to false.

**Comment by Agontuk** [comment]
You can try the master branch to test if location request works in airplane mode.

**Comment by Agontuk** [comment]
This is already fixed in newer versions, now it'll try to get a location fix. But it's not guaranteed.
