### ISSUE TITLE
undefined is not a function (near '...(0, _reactNativeGeolocationService.watchPosition)

### ISSUE THREAD

**Issue by CharukaHS** [Agontuk/react-native-geolocation-service#284]
Device Info:
Android emulator: API 29
react-native-geolocation-service@5.3.0-beta.1
react-native@0.63.3

I tried the simplest code for Geolocation.watchPosition
```ts
const options: GeoOptions = {
  accuracy: {android: 'high'},
  enableHighAccuracy: true,
};

try {
  watchPosition(
    (position) => {
      console.log(position);
    },
    (error) => {
      console.error(error);
    },
    options,
  );
} catch (error) {
  console.error(error);
}
```

Neither IDE nor ESLint throw up errors, but when I run the app, this error appears.  
`[TypeError: undefined is not a function (near '...(0, _reactNativeGeolocationService.watchPosition)...')]`

Same error for the `getCurrentPosition` 

Had to wrap the watchPosition inside a try catch to get this error, otherwise the error message starts with "Possible Unhandled Promise Rejection". (see the below image)

![image](https://user-images.githubusercontent.com/11798029/121792638-2abf5c00-cbe7-11eb-8eaf-d5e5799a61d8.png)

**Comment by khlling** [comment]
I'm also getting the same error on the react-native-geolocation-service@5.3.0-beta.1 on iOS

**Comment by Agontuk** [comment]
Most probably a setup issue, try reinstalling the package again. Also check if react native picks up the package during `pod install` or `react-native run-android`

**Comment by CharukaHS** [comment]
Changing
```ts
import {  watchPosition } from 'react-native-geolocation-service'
```

to 
```ts
import Geolocation from 'react-native-geolocation-service';
Geolocation.watch()
```

fixed the issue
