### ISSUE TITLE
Polyline not very accurate on IOS

### ISSUE THREAD

**Issue by HybridChronus** [Agontuk/react-native-geolocation-service#292]
Hello, 

I'm having issues with polyline accuracy specifically with IOS. Android works great and the polyline stays on the road. 

Below is an example of a test drive on IOS:

![Polyline issue](https://user-images.githubusercontent.com/3676669/124837723-a8565d80-df42-11eb-84be-c27e6faf6e25.png)

Despite having it set to "enableHighAccuracy" it doesn't seem to want to stay on the road.  I've tried disabling the setting and then setting the accuracy myself, but it didn't change much.

My current settings for watchPosition and currentPosition:
`  const watchOptions: GeoLocation.GeoWatchOptions = {
    enableHighAccuracy: true,
    distanceFilter: 10,
    interval: 5000,
  };`

Is there a setting I'm using incorrectly or one I'm missing entirely?

Thank you.

**Comment by LightKnight3r** [comment]
i suggest you should use google api to fix routes(snap-to-road)
