### ISSUE TITLE
Need to declare foreground service? 

### ISSUE THREAD

**Issue by aruhn1** [Agontuk/react-native-geolocation-service#295]
As stated in the [location permission docs](https://developer.android.com/training/location/permissions), 

> The system considers your app to be using foreground location if a feature of your app accesses the device's current location in one of the following situations:
>  An activity that belongs to your app is visible.
>  Your app is running a foreground service. When a foreground service is running, the system raises user awareness by showing a persistent notification. Your app retains access when it's placed in the background, such as when the user presses the Home button on their device or turns their device's display off.
> Additionally, it's recommended that you declare a foreground service type of location, as shown in the following code snippet. On Android 10 (API level 29) and higher, you must declare this foreground service type.

> You declare a need for foreground location when your app requests either the ACCESS_COARSE_LOCATION permission or the ACCESS_FINE_LOCATION permission, as shown in the following snippet:

> On Android 10 (API level 29) and higher, you must declare this foreground service type.

So does this need to be done, as suggested in the docs, by adding something like 
```
<service
    android:name="MyNavigationService"
    android:foregroundServiceType="location" ... >
    <!-- Any inner elements would go here. -->
</service>

```
?

**Comment by pedrotrogo-fump** [comment]
+1

**Comment by Agontuk** [comment]
yes, you can add it to your project if you want foreground service. You can follow the example project
[https://github.com/Agontuk/react-native-geolocation-service/blob/master/example/android/app/src/main/AndroidManifest.xml#L31](https://github.com/Agontuk/react-native-geolocation-service/blob/master/example/android/app/src/main/AndroidManifest.xml#L31)
