### ISSUE TITLE
How to get rid of blue bar in background

### ISSUE THREAD

**Issue by junaidrazaq** [Agontuk/react-native-geolocation-service#298]
I'm using the watchPosition function and the location is being tracked successfully, but for some reason, the location is being tracked in the background also. I don't mind this but the blue bar is showing on the top when the app is in the background. How could i go about removing this? Thanks

` handlePermission = async unmount => {
        let isGranted;

    if (Platform.OS === 'android') {
      isGranted = await request(PERMISSIONS.ANDROID.ACCESS_FINE_LOCATION);
    } else {
      isGranted = await request(PERMISSIONS.IOS.LOCATION_WHEN_IN_USE);
    }
    if (isGranted === RESULTS.GRANTED) {
      const _watchId = Geolocation.watchPosition(
        position => {
          const {latitude, longitude} = position.coords;
          setCurrentLocation({lat: latitude, lng: longitude});
        },
        error => {
          console.log(error);
        },
        {
          enableHighAccuracy: true,
          timeout: 1000,
          distanceFilter: 100,
          interval: 5000,
          fastestInterval: 2000,
        },
      );
      if (unmount === 'unsubscribe') {
        console.log('removing listeners');
        Geolocation.clearWatch(_watchId);
      }
    }
    }

    useEffect(() => {
      handlePermission();

      return () => {
        handlePermission('unsubscribe');
      };
    }, []);`

**Comment by JunaidRazaqNearU** [comment]
Doesn't work. I have version 5.0.0. Maybe this is why? I'll try to upgrade versions and see if it works, thanks

**Comment by junaidrazaq** [comment]
Doesn't work. I have version 5.0.0, maybe that's why? I will try to upgrade and let you know if that works, Thanks

**Comment by JunaidRazaqNearU** [comment]
Nope, version 5.0.0 and same issue. On IOS btw

**Comment by junaidrazaq** [comment]
Nope, same issue on version 5.0.0. IOS btw

**Comment by ivangonzalezg** [comment]
You have to enable location updates capability for your app in Xcode. 

1. Open Xcode
2. Click on your app name
3. Open Signing & Capabilities
4. Add Background mode to capabilities (if not added)
5. Check Location updates

![image](https://user-images.githubusercontent.com/42500072/157536312-049b43c3-9f5a-46b6-a806-a8606a9e81d7.png)

Now you can use the watchPosition function and then when your app go to background the blue bar appears

![image](https://user-images.githubusercontent.com/42500072/157536752-98df3197-3b21-495a-ac51-a7598a4e71c5.png)

![image](https://user-images.githubusercontent.com/42500072/157535422-07ca429f-b9e1-4f6e-9438-2a38e0c749eb.png)

**Comment by marquina-abreu** [comment]
I think that to collect the coordinates in background mode, it only works for iOS... for android it doesn't... I think that for that case you have to resort to another library that is paid

**Comment by Agontuk** [comment]
Setting `showsBackgroundLocationIndicator: false` will only work if you're using `always` authorization. If you're using `whenInUse` authorization, it'll always show the blue bar. I hope it clears the confusion.

[https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator](https://developer.apple.com/documentation/corelocation/cllocationmanager/2923541-showsbackgroundlocationindicator)
