### ISSUE TITLE
Permission doesn't popup in Release version

### ISSUE THREAD

**Issue by lucas-dolsan** [Agontuk/react-native-geolocation-service#30]
When requesting a location using  **Geolocation.getCurrentPosition**, if the location service is not enabled on the device, a message requesting user's permission pops up.

This has worked fine in the past, in debug versions and in release versions 
* react-native run-android;
* react-native run-android --variant=release

_the image is in portuguese, my device's default language_
![15baf29b-8627-4b10-a4c2-c0f49e55aee3](https://user-images.githubusercontent.com/27600001/42760626-6f0f53d4-88e1-11e8-8a97-0ac7ba16e10c.jpg)

 __Issue:__
In release versions, the pop up simply doesn't appear when a location request is made

``` 
react-native-cli: 2.0.1
react-native: 0.53.0
react-native-geolocation-service: 1.0.4 And 1.1.0
```
__Edit:__
Also, the problem happens with android versions ``` 6.0 ``` and ``` 7.1.1 ```

**Comment by Agontuk** [comment]
Did you set the `showLocationDialog` to false ? If yes, it'll return an error response with code 5. Otherwise location dialog should appear.

**Comment by lucas-dolsan** [comment]
my config to the **getCurrentLocation** function looks like this: 

```{ enableHighAccuracy: true, timeout: 3500, maximumAge: 0 } ```
Your documentation says  ```showLocationDialog ``` defaults to true.

Still, as I said, it works fine on the debug version, but when assembling a release, the resulting apk does not pop up the message

**Comment by Agontuk** [comment]
Are you not getting any response from success/error callback ? If not, please check the logcat for possible errors and share it here.

**Comment by lucas-dolsan** [comment]
Apparently my issue has resolved itself, it's now working fine again =p
