### ISSUE TITLE
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

### ISSUE THREAD

**Issue by andreialecu** [Agontuk/react-native-geolocation-service#301]
Getting the warning:

```
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

In React Native 0.65.

Related line:
https://github.com/Agontuk/react-native-geolocation-service/blob/ffc3cc301420e72ab32b38a83907eb76997ccc45/js/Geolocation.native.js#L4

**Comment by Agontuk** [comment]
> Here's a diff from a different package that fixes this warning:
> 
> https://github.com/software-mansion/react-native-reanimated/pull/2316/files
> 
> Should be easy to fix if someone can test it and submit a PR.

Thanks for the link, I'll try fixing it as soon as possible.

**Comment by EverStarck** [comment]
Hi
I saw a commit fixing this warning but it still appears in the same way as op said. I'm in `react-native: 0.65.1` and in `react-native-geolocation-service": "^5.3.0-beta.2`

**Comment by andreialecu** [comment]
There was no release made with this particular fix yet. `5.3.0-beta.2` is a couple of months old.

**Comment by EverStarck** [comment]
> There was no release made with this particular fix yet. `5.3.0-beta.2` is a couple of months old.

Oh right 😅😅. Thanks for answering

**Comment by Agontuk** [comment]
new version published

**Comment by ClaraGaya** [comment]
Hi,
I'm still getting the issue, I'm in "react-native": "0.66.2", and in "react-native-geolocation-service": "^5.3.0-beta.3"

**Comment by freemanUA** [comment]
why it is closed?

**Comment by suresh03** [comment]
react-native-otp-inputs
 this package also same this issues how to fix it please help me

**Comment by gomezmark** [comment]
anyone solved this issue?
Thanks
