### ISSUE TITLE
error: Location settings are not satisfied.

### ISSUE THREAD

**Issue by andkom** [Agontuk/react-native-geolocation-service#304]
Earlier I've used `react-native-maps`'s fused location provider and everything worked fine.
After I switched to `react-native-geolocation-service` some users reported that they don't receive location updates.

Version: 5.2.0

Code:

```
const useLocation = () => {
  const dispatch = useDispatch();

  useEffect(() => {
    if (!locationPermission) {
      return;
    }

    const watchId = GeoLocation.watchPosition(
      (geoPosition) => {
        dispatch(...);
      },
      (err) => {
        console.warn('Unable to get location', err);
      },
      {
        enableHighAccuracy: true,
        distanceFilter: 0,
        interval: 5000,
        fastestInterval: 1000,
        showLocationDialog: false,
        forceRequestLocation: true,
      },
    );

    return () => {
      GeoLocation.clearWatch(watchId);
    };
  }, [dispatch, locationPermission]);

  return null;
};

```

Steps to duplicate:
- disable WiFi and bluetooth
- restart phone 
- request watchPosition
- watchPosition fails with error `{ message: 'Location settings are not satisfied.', code: 5 }` despite `forceRequestLocation: true`
- other applications show user location

If I set `showLocationDialog` to `true` and then reject  location dialog, `watchPosition` returns location successfully.

**Comment by frankbolviken** [comment]
Did you manage to solve this? Getting the same on some devices

**Comment by andkom** [comment]
@frankbolviken not yet, I use this lib with `showLocationDialog: true`

**Comment by frankbolviken** [comment]
I mean. Just closing the issue without any comments. I like it.

**Comment by Agontuk** [comment]
Github automatically closes issues when relevant fixes are pushed :)
