### ISSUE TITLE
when netWork is offline  it is not  work 

### ISSUE THREAD

**Issue by tiyunchen** [Agontuk/react-native-geolocation-service#31]
when netWork is offline  it can not  getPosition just show Location request time out

**Comment by Agontuk** [comment]
This library currently does not support fetching location in offline mode, since google play service does not allow it.

**Comment by NULL-SWEAT** [comment]
Would be nice to update the readme with this information...

**Comment by pavelkeyzik** [comment]
Doesn't work if I use cellular data. Wi-Fi works pretty well.

- Phone: Meizu M6 Note (Android 7.1.2)
- react-native: 0.57.7
- react-native-geolocation-service: 1.1.0

**Comment by Agontuk** [comment]
Closing this, you can try with `forceRequestLocation: true` in newer version to get location in network offline mode. But it is not guaranteed.
