### ISSUE TITLE
Consider bumping Android play-services version to 19

### ISSUE THREAD

**Issue by fiznool** [Agontuk/react-native-geolocation-service#333]
On Android, this package currently uses `play-services-location` v17 by default. This was [originally released in June 2019](https://developers.google.com/android/guides/releases#june_17_2019). Since then, versions 18 and 19 have been released - looking through the release notes, there have been a few fixes to this dependency, including one in v18 that [suppresses initial inaccurate results by default](https://developers.google.com/android/guides/releases#february_18_2021).

I understand it is possible to override the version used in a project by defining the `googlePlayServicesVersion` in the project gradle file, but since many people will not do this, perhaps it is time to consider bundling the latest version (19) of the play-services-location dependency by default?

**Comment by cristianoccazinsp** [comment]
Hey, what are the benefits of using v 19? I'm also using v18.

**Comment by fiznool** [comment]
I don't think there is anything different from a feature perspective. The major version bump is because the native library was changed to use 'strict null' annotations. 

https://developers.google.com/android/guides/releases#december_09_2021

I don't imagine there are any real-world differences between using v18 and v19 for this package.

**Comment by Agontuk** [comment]
Thanks @fiznool for the info. I've updated the default version to 18.0.0 as v19 does not seem to have any location related changes. Closing this for now.
