### ISSUE TITLE
watchPosition is not yet implemented

### ISSUE THREAD

**Issue by tiyunchen** [Agontuk/react-native-geolocation-service#36]
i test in my code and also test resource code , it alway show this warning, have any solution

**Comment by oakis** [comment]
"watchPosition is not yet implemented" basically means that the method watchPosition does not exists yet. Not 100% sure but that is what the message says.

**Comment by Agontuk** [comment]
You're probably using an old version, try the 1.1.0 version.

**Comment by tiyunchen** [comment]
thank you , i will try it

**Comment by tiyunchen** [comment]
i can't install it show couldn't  find match

**Comment by oakis** [comment]
Just tried it now and I don´t have any problems.

```
$ npm install react-native-geolocation-service@^1.1.0
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ react-native-geolocation-service@1.1.0
added 1 package from 1 contributor in 1.638s
[+] no known vulnerabilities found [1 packages audited]
```

**Comment by tiyunchen** [comment]
`D:\reactNativeTestWork\ridecomfortapp>npm install react-native-geolocation-service@^1.1.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for react-native-geolocation-service@1.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
`

**Comment by tiyunchen** [comment]
so wired

**Comment by oakis** [comment]
What if you omit @^1.1.0?

**Comment by tiyunchen** [comment]
it's ok when i  omit `@^1.1.0` and also `npm install react-native-geolocation-service@^1.0.4` is fine

**Comment by tiyunchen** [comment]
i can only install package version is 1.0.4, execute `npm install react-native-geolocation-service`  return version is 1.0.4 . i am in china.

**Comment by tiyunchen** [comment]
i know why `Administrator@PC-20180412BLNS MINGW64 /d/reactNativeTestWork/vibration (master)
$ npm info react-native-geolocation-service
react-native-geolocation-service@1.0.4 | MIT | deps: none | versions: 5
React native geolocation service for iOS and android
https://github.com/Agontuk/react-native-geolocation-service
dist
.tarball http://registry.npm.taobao.org/react-native-geolocation-service/download/react-native-geolocation-service-1.0.4.tgz
.shasum: 02ca4ddec147ed4cb0c4cc8106eb7c6f00708818
maintainers:
- agontuk <rifat662@gmail.com>
dist-tags:
latest: 1.0.4
published 4 months ago by agontuk <rifat662@gmail.com>
`

**Comment by tiyunchen** [comment]
i install success , my method is git clone your last version in my node_module

**Comment by tiyunchen** [comment]
and  it works

**Comment by Agontuk** [comment]
1.1.0 is published on npm, don't know why this is happening. Is this a region specific issue ? I'll close this for now, feel free to open if you face further issue.
