### ISSUE TITLE
How to check precise location status on iOS devices?

### ISSUE THREAD

**Issue by tunm1228** [Agontuk/react-native-geolocation-service#365]
![image](https://user-images.githubusercontent.com/42457760/178461416-9d104773-3eb4-4f64-b150-c0d40a5534b8.png)

**Comment by Pardiez** [comment]
Hi @tunm1228 
This library is about geolocation, not (geolocation or other) permissions. 
Have you tried https://github.com/zoontek/react-native-permissions?

**Comment by Agontuk** [comment]
@tunm1228 , as suggested above use `react-native-permissions` library. I'll remove permission related API in future major release
