### ISSUE TITLE
Xcode Issue with building app

### ISSUE THREAD

**Issue by ceyanesb** [Agontuk/react-native-geolocation-service#374]
Undefined symbols for architecture x86_64:
  "_OBJC_METACLASS_$_RCTEventEmitter", referenced from:
      _OBJC_METACLASS_$_RNFusedLocation in RNFusedLocation.o
  "_OBJC_CLASS_$_RCTEventEmitter", referenced from:
      type metadata for react_native_geolocation_service.RNFusedLocation in RNFusedLocation.o
  "_RCTMakeAndLogError", referenced from:
      react_native_geolocation_service.checkPlistKeys(Swift.String) -> () in LocationUtils.o
  "_RCTRegisterModule", referenced from:
      _initialize_RNFusedLocation in RNFusedLocationBridge.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

React Native Info
```
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.61 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.02.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 32.0.0, 33.0.0
      System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7935034
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.8 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by ceyanesb** [comment]
@Agontuk any help? This is happening after installing react-native-firebase for which you need to disable flipper and enable use_frameworks! for it to work. Please help urgen

**Comment by Agontuk** [comment]
please provide e sample repo if you can which reproduces the crash

**Comment by Y-k-Y** [comment]
@ceyanesb Did you find the solution for it?

**Comment by Agontuk** [comment]
I tried building with `use_frameworks! :linkage => :static` and it built without any issue.

**Comment by ceyanesb** [comment]
> @ceyanesb Did you find the solution for it?
> 
> 
> 
> 

The problem was a combination of this library, react-native-firebase and react-native-stripe. It as a compatibility thing and the best thing I could do without using deprecated code was to upgrade my react native version from 0.67.4 to 0.68.3

**Comment by Agontuk** [comment]
> The problem was a combination of this library, react-native-firebase and react-native-stripe. It as a compatibility thing and the best thing I could do without using deprecated code was to upgrade my react native version from 0.67.4 to 0.68.3

I tried with RN 0.70, maybe that's why it worked fine. Glad you found a solution. Closing this for now.

**Comment by JulioRosil** [comment]
Got the same, can't fix it

**Comment by tamdvyounetgroup** [comment]
any solution?
