### ISSUE TITLE
Getting {"code": 2, "message": "Unable to retrieve location due to a network failure"} on IOS

### ISSUE THREAD

**Issue by SurajMohanty02** [Agontuk/react-native-geolocation-service#396]
On ios , when i request for location i'm getting {"code": 2, "message": "Unable to retrieve location due to a network failure"} . Please provide some solution.

**Comment by matheusyuri7** [comment]
I'm facing the same issue

**Comment by SurajMohanty02** [comment]
@matheusyuri7 try to set Custom Location in Mac.

**Comment by SonuGitCfcs** [comment]
Let me correct this, try to set Custom Location in Simulator.
![Screenshot 2024-02-05 at 1 57 36 PM](https://github.com/Agontuk/react-native-geolocation-service/assets/108975414/41b745db-b827-4b53-b5f6-a99cddf2d8f4)
