### ISSUE TITLE
WARNING: Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.

### ISSUE THREAD

**Issue by Shhzdmrz** [Agontuk/react-native-geolocation-service#42]
Getting multiple warning any plan to upgrade project before end of the year?

> WARNING: Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.
> It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'

**Comment by Shhzdmrz** [comment]
@Agontuk you can make two version like until now for gradle 2 and the newer for gradle 3. Because of google condition all people are going to use it even react native 0.57.0 also targeting it.

**Comment by Agontuk** [comment]
Ok, I'll take a look. Haven't used 0.57 yet.
