### ISSUE TITLE
Location request timed out

### ISSUE THREAD

**Issue by AngSin** [Agontuk/react-native-geolocation-service#5]
Hi Agontuk, I hope I'm doing something wrong, I cloned the repository, `cd example && npm i` 

I have turned on the high accuracy location service on my phone and allowed the example app to access my location but I'm getting error code 3, "Location request has timed out." when running the app (same behaviour as React Native's Geolocation API). Did I miss a step?

**Comment by Agontuk** [comment]
Probably not, many devices have this issue. I've added a [FAQ](https://github.com/Agontuk/react-native-geolocation-service#faq) section for some possible solution, check if it helps you. Also try with `enableHighAccuracy: false, distanceFilter: 0`.

**Comment by kholiavko-roman** [comment]
@Agontuk I found an issue: if I setup location mode settings in 'Power Save mode' or 'Device Only', when I press the button to get location, plugin show dialog window: that for better result I need enable 'High accuracy mode', but if I press "Ok" - location always will return error 'Location time out'
But if I reinstall example application and run it with enabled 'High accuracy' mode - all works fine.
[Here is a video of reproducing a problem.](https://photos.app.goo.gl/wnQCNNKlnZtzTBov1)

**Comment by Agontuk** [comment]
I tried to reproduce the issue, but it works fine on my Xiaomi Redmi Note 3 device. Can you try adding `distanceFilter: 0` to the options and see if it helps ?

**Comment by kholiavko-roman** [comment]
I already try different configuration, and with this configuration it works if I enable  'Power Save mode'  in geolocation options (dialog window that asks to enable 'high accuracy' doesn't show in this case)
` { timeout: 15000, maximumAge: 10000, enableHighAccuracy: false, distanceFilter: 0 }`
But if I enable 'Device only' options in geolocation settings - this window shows, and it stops work - always show error 'Location time out'.

**Comment by kholiavko-roman** [comment]
Maybe as temporary solution I can disable this window ? Can you help me please, how to disable it in code ?

**Comment by kholiavko-roman** [comment]
I found the similar problem with google maps. I think I have a problem with device. But anyway thanks for helping!

**Comment by CorentinDupont** [comment]
Hi everyone, I had the same problem. But when i am outdoor, all work fine ! So think about that ;)
