### ISSUE TITLE
Prompt only if location disabled completely?

### ISSUE THREAD

**Issue by nol13** [Agontuk/react-native-geolocation-service#51]
If they have location on their device set to gps only, would it be possible/desirable to use gps and not prompt them to enable location even if enableHighAccuracy = false?

Like if they have location turned off, always prompt, if on, then use low accuracy,  but if on and set to gps only, then just use gps and don't prompt?

Possibility am unclear on how this differs from built-in geolocation, but am trying to achieve reliable location, and do want to prompt if they're someone who only enables location from the status bar when needed, but also avoid unnecessarily requiring them to give their location to google if they've explicitly chosen not too.

**Comment by Agontuk** [comment]
google play service probably does not allow requesting location in "GPS Only" mode. That's why it shows the prompt to enable high accuracy mode. But I'll check if it can be done.
