### ISSUE TITLE
watchPosition doesn't raise an error if the user disables location services

### ISSUE THREAD

**Issue by yoshikischmitz** [Agontuk/react-native-geolocation-service#53]
When a user opens the app with location services enabled, and the app then registers a `watchPosition` callback, and then the user _disables_ location services, and goes back to the app, `watchPosition` never raises an exception. React Native core's navigator.geolocation has this same issue, but I would expect `watchPosition` to raise an exception the same way that `getCurrentPosition` would. This would be useful for detecting that location services are off so the app could prompt a user to reenable it.

**Comment by oakis** [comment]
I think this is what you are looking for:
https://facebook.github.io/react-native/docs/permissionsandroid

**Comment by Agontuk** [comment]
You mean the error callback is not triggered ? That seems like a bug, I'll look into it.

**Comment by yoshikischmitz** [comment]
@Agontuk yes the `onError` callback on `watchPosition` is not triggered. To be clear, the `onError` callback on `getCurrentPosition` does get triggered.

**Comment by avasuro** [comment]
Same issue.
And in addition: If I run my application with disabled GPS, then i click "No thanks" on request to turn GPS on (after that errorCallback is triggering), and then I manually turn GPS on - nothing happens after that (I expect that successCallback should be triggered).

**Comment by ThePJMP** [comment]
@Agontuk is there any update on this issue?

**Comment by Agontuk** [comment]
It should be fixed in v5.0.0. Sorry for not being able to fix this sooner.
