### ISSUE TITLE
Running on Android 9.0 in vscode

### ISSUE THREAD

**Issue by maeneak** [Agontuk/react-native-geolocation-service#54]
Just thought i'd provide some feedback. To get this going on Andoid 9 (Pie) i did the following:

1. terminal `npm i react-native-geolocation-service`
2. terminal `react-native link react-native-geolocation-service`
3. insert the following into `android\app\build.gradle` in the `dependencies {...}` section
    `implementation "com.google.android.gms:play-services-location:16.0.0"`

I was also had problems with red screens on launch when debugging. Deleting the `android\build` folder before deployment fixed this for me

**Comment by Agontuk** [comment]
Closing this since it's not an issue, thanks for providing feedback.
