### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by RWOverdijk** [Agontuk/react-native-geolocation-service#58]
Maybe add typescript typings? It's as easy as doing this:

```ts
declare module "react-native-geolocation-service" {
  export default navigator.geolocation;
}
```

**Comment by Agontuk** [comment]
Typescript typings is merged now.

**Comment by slavikdenis** [comment]
When could this be released? Thanks :)

**Comment by drew-r** [comment]
Yes please release or we have to install from GH :)

**Comment by Agontuk** [comment]
v2.0.1 is published with the typescript typings
