### ISSUE TITLE
Not getting exact latitude longitude on ios device using watchPosition.

### ISSUE THREAD

**Issue by archana-iron** [Agontuk/react-native-geolocation-service#62]
**Issue Description::**

I am working on react native tracking application. Basically users check in  from a certain place and they need to reach at the destination. Using this application we are finding out the path they are following. I need to get a geocodes from users check in location to destination to track the path he is following.
Now it builds a clean path in case of Android device, but having an issue with ios. For ios it takes a huge variation inside code.
I have tested this by traveling to same place using both devices(ios and android). For Android it's generates a exact latitude longitude values, but for ios there is a huge variation. Why this is happening. I have followed the official doc of react native for geolocation setup.
You can check this link:: https://facebook.github.io/react-native/docs/geolocation.html#ios

This is happening when I have updated react native version to 0.58

**Environment I am using ::** 
React Native: 0.58
react-native-geolocation-service: 2.0.0

**Comment by Agontuk** [comment]
This library is using the default react native location module for iOS. So if you're having a problem, that means it's an issue with RN module. So it'll be better if your open a issue in RN repo.

**Comment by archana-iron** [comment]
Now I have made changes in react-native/Libraries/Geolocation/RCTLocationObserver.m . You can check this link:: [Link](https://github.com/reyalpsirc/react-native/commit/408d949ae35c2fd9ff8055022815913bd652bf1a)
After making these changes, it works fine on ios. Is this accurate method or not??

**Comment by Agontuk** [comment]
Can't tell, but looks like it should have been configurable from user end.

**Comment by omnikron** [comment]
This was a bug with React Native iOS Geolocation Library. It is fixed in react-native 0.59: https://github.com/facebook/react-native/commit/bbcb97a29adc2a3a05728b47d28e28fa78d84df2

**Comment by Agontuk** [comment]
Closing this since it's been fixed in 0.59.
