### ISSUE TITLE
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.

### ISSUE THREAD

**Issue by QiZhongdd** [Agontuk/react-native-geolocation-service#63]
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
More than one file was found with OS independent path 'META-INF/rxjava.properties'

**Comment by a1lu** [comment]
Got the same problem, for me this helped:

```
packagingOptions {
   exclude 'META-INF/rxjava.properties'
}
```


see for example: https://github.com/ReactiveX/RxJava/issues/4445

**Comment by Agontuk** [comment]
Looks like it can be solved by following the link, closing this for now.
