### ISSUE TITLE
iOS does not display permission modal without all location keys

### ISSUE THREAD

**Issue by phillipkey** [Agontuk/react-native-geolocation-service#67]
Currently, the only way to get the permissions modal to fire for iOS is by including all of the following location keys in the Info.plist file:

```
<key>NSLocationAlwaysUsageDescription</key>
<string>some string</string>
<key>NSLocationWhenInUseUsageDescription</key>
<string>some string</string>
<key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
<string>some string</string>
<key>NSLocationUsageDescription</key>
<string>some string</string>
```

we do not ever need the LocationAlways permission and this seems strange to ask users.

**Comment by Agontuk** [comment]
This package uses the default iOS module from react-native, so it's probably an issue with the react-native core module. But last time I checked, I only used the NSLocationUsageDescription and it worked fine for me. If it's not working now, please create an issue in RN repo.

**Comment by phillipkey** [comment]
ok. i'll do so. Thanks @Agontuk
