### ISSUE TITLE
Update package to use react-native-geolocation

### ISSUE THREAD

**Issue by oakis** [Agontuk/react-native-geolocation-service#69]
Geolocation is being removed in RN 0.60 and is moved to https://github.com/react-native-community/react-native-geolocation

**Comment by JanithaR** [comment]
What do you mean by the title? Isn't this package a solution (alternative) for react-native-geolocation?

**Comment by oakis** [comment]
@JanithaR Reference: https://github.com/facebook/react-native/issues/7495#issuecomment-481597534

**Comment by JanithaR** [comment]
I know that and the recommended approach is to use
react-native-geolocation-service instead of react-native-geolocation. I'm
just still wondering what you meant in the question.

Regards,
Janitha

**Comment by Agontuk** [comment]
`react-native-geolocation` is needed because this package uses RN's default implementation for iOS. Since it's moved into a separate repo we have to integrate that too.

**Comment by canpoyrazoglu** [comment]
I've forked the repo (feel free to use if you need it before this repo is officially updated) at https://github.com/canpoyrazoglu/react-native-geolocation-service. (Though you'll need to add and link the dependency manually, see below.)

I can confirm that it works (at least, on iOS, couldn't test Android yet) after adding the `geolocation` package:

`yarn add @react-native-community/geolocation`

Linking it:
`react-native link @react-native-community/geolocation` 

And referencing it in `index.js`:
`import Geolocation from '@react-native-community/geolocation'`

And also deleting the line:
`let Geolocation = global.navigator.geolocation;`
(as we'll be using the imported version as the same variable).

I'm on RN 0.60 RC2 and can confirm it works correctly on my device (iPhone X, iOS 12.3.1).

**Comment by eisenheim94** [comment]
@canpoyrazoglu no, on Android it says "Geolocation" is read-only. But I think that this error must be on iOS too

**Comment by eisenheim94** [comment]
But I have RN 0.59.9

**Comment by Agontuk** [comment]
Sorry guys, I've been pretty busy with work lately so haven't pushed an update regarding this. I'll fix this tonight.

**Comment by Agontuk** [comment]
I've pushed a commit in master branch to fix this, please try and let me know if it works. I'll then release it in npm registry.

**Comment by c-schuette** [comment]
Hey, anythink new about adding it to the npm registry? And thanks for this helpful package :)

**Comment by Agontuk** [comment]
New version is already available in npm.
