### ISSUE TITLE
So much curious if this could function in China mainland?

### ISSUE THREAD

**Issue by flyinghawker** [Agontuk/react-native-geolocation-service#71]
The project needs geolocation functionality for China mainland area, but so far no good lib available in React Native. Not sure if this could be applied right there.

**Comment by Agontuk** [comment]
As far as i know, google play service does not work in china. Unfortunately there's nothing I can do if that's the case.

**Comment by flyinghawker** [comment]
@Agontuk Thank you, my friend. I will try to test it anyway.

**Comment by Kuhne1** [comment]
@flyinghawker Did it work in China?
