### ISSUE TITLE
MainApplication.java new RNFusedLocationPackage(); close application

### ISSUE THREAD

**Issue by marciodiasdeveloper** [Agontuk/react-native-geolocation-service#75]
After adding the new RNFusedLocationPackage () call to my MainApplication.java file the application hangs

**Comment by Agontuk** [comment]
Provide details please. Also make sure you followed the instruction correctly.

**Comment by tirafaelmendonca** [comment]
I'm having the same problem. When I added the library my project does not open anymore.

I configured settings.gradlew
I configured build.gradlew
I configured the app / build.gradlew
I configured MainApplication.java

As step by step

**Comment by rewieer** [comment]
Replace 
```
        googlePlayServicesVersion = "11.0.0"
```

By
```
        googlePlayServicesVersion = "16.0.0"
```

In your app build.gradle. See [this](https://stackoverflow.com/questions/51388073/failed-resolution-of-lcom-google-android-gms-common-api-apizzf) for more informations.

**Comment by Agontuk** [comment]
Please follow the steps again if you can, I've updated the README for 0.60. Closing this for now, feel free to create new issue if problem persists.
