### ISSUE TITLE
How to improve the accuracy

### ISSUE THREAD

**Issue by sirajahmad1** [Agontuk/react-native-geolocation-service#77]
Hi,

please anyone help me to improve the accuracy of the location, i am getting accuracy between 22-26 (even in open space)
sometime it's giving 104

**Specifications**

"react-native": "0.59.8",
"react-native-geolocation-service": "^2.0.1",

**Here is my code** 

`Geolocation.getCurrentPosition(
   (position) => {
       console.log('position', position);

   },
   (error) => {
       // See error code charts below.
       console.log(' error position',error.code, error.message);
   },
   { enableHighAccuracy: true, timeout: 30000, maximumAge: 0 }
);`

**Output**

> coords:
accuracy: 26.351999282836914
altitude: 160.60000610351562
heading: 0
latitude: 28.6310836
longitude: 77.3841066
speed: 0

**Comment by ravimalviya688** [comment]
I am also looking for same thing

**Comment by smaldd14** [comment]
I, too, am looking to improve accuracy of longitude and latitude I am getting back... Please let me know if there is a solution

**Comment by Agontuk** [comment]
Currently I don't know any other way to improve this. If I find anything, I'll let you know. Same goes for anyone finding a solution.

**Comment by oakis** [comment]
Might be your devices. I had problems with accuracy on both my OP1 and OP3 phones.
If possible try with a device that is known for good GPS accuracy.

**Comment by Agontuk** [comment]
You can try calibrating your device compass, it'll help with the location accuracy.

**Comment by iaaltojarvi** [comment]
Same problem here. Calibrating does not help. Accuracy fluctuates between 16-30, but it should be under 10 in our case.

**Comment by nes123** [comment]
I get > 1000m accuracy many times. Is it reasonable?

**Comment by Agontuk** [comment]
Closing this as it is not a library issue. GPS accuracy depends on device and the environment you're in. It's out of our hands, we're just providing what native library gives us. You can filter out the locations with bad accuracy from the app side.
