### ISSUE TITLE
Debug sounds should respect the device volume (nice to have)

### ISSUE THREAD

**Issue by jaltin** [Agontuk/react-native-geolocation-service#78]
It is really helpful having the sounds playing for debugging purposes by setting 'debug: true'.

As it is now, the sound is played in the same volume no matter what volume I have on my device (tested on an iPhone XS with plugin version 3.0.4 and react native 0.57.2) .

It would be nice if the sound playing respected the volume settings, so that when I am going around and doing real world tests, I could lower the volume to a barely audible level that I can hear, but that doesn't bother people in my surroundings.

**Comment by Agontuk** [comment]
I don't understand how this is related to the project. Please clarify, for now I'm closing this.
