### ISSUE TITLE
How to control the location services status bar (Blue Bar) for IOS

### ISSUE THREAD

**Issue by NooruddinLakhani** [Agontuk/react-native-geolocation-service#80]
In IOS, how do I turn on or off the Location Services Status Bar (Blue Bar) for my app while it is in the background?

Starting with iOS 11, an app can toggle the **showsBackgroundLocationIndicator** property to change the visibility of the blue bar at any time.
Reff : https://developer.apple.com/library/archive/qa/qa1965/_index.html

Currently I'm using **react-native-geolocation-service** 
https://github.com/Agontuk/react-native-geolocation-service

How can I use **showsBackgroundLocationIndicator** in **react-native-geolocation-service** library ? Is there any possibility?

**Comment by Agontuk** [comment]
This library uses [https://github.com/react-native-community/react-native-geolocation](https://github.com/react-native-community/react-native-geolocation) for iOS module. It would be better to create an issue there about this.
