### ISSUE TITLE
Incompatible with googlePlayServicesVersion 16.1.0

### ISSUE THREAD

**Issue by joaom182** [Agontuk/react-native-geolocation-service#81]
My project uses googlePlayServicesVersion 16.1.0 and the package `com.google.android.gms:play-services-location:16.1.0` not exists. This is throwing build errors.

Any sugestions?

**Comment by Alexispap** [comment]
Use 16.0.0. There is no version 16.1.0 for the location package at the moment.

**Comment by JanithaR** [comment]
https://mvnrepository.com/artifact/com.google.android.gms/play-services-location/16.1.0

**Comment by joaom182** [comment]
@JanithaR i see that, but the package really not exist on ICM repository. I don't know why the Maven is listing that.

**Comment by Agontuk** [comment]
Closing this since it's not related the package itself.
