### ISSUE TITLE
[TypeScript] GeoErrorCode enum is declared only in index.d.ts but not in JS code

### ISSUE THREAD

**Issue by tsvetan-ganev** [Agontuk/react-native-geolocation-service#82]
First of all, thank you for developing this package which solves a really painful inconsistency between iOS and Android geolocation implementations.

Recently I saw that you added typings and I upgraded to the newest version to try them out. However, I found an issue - [the following line](https://github.com/Agontuk/react-native-geolocation-service/blob/master/index.d.ts#L21) in the `index.d.ts` file declares an enumeration with the error codes, but when users import it in their TypeScript code, it resolves to `undefined` since it's not declared anywhere in JavaScript land. The reason is that the TypeScript compiler doesn't generate any JavaScript code for type definitions (`.d.ts` files).

The solution is to declare the error codes as a regular object in the `index.js` file as well and export it.

```js
export const GeoErrorCode = {
    PERMISSION_DENIED: 1,
    POSITION_UNAVAILABLE: 2,
    TIMEOUT: 3,
    PLAY_SERVICE_NOT_AVAILABLE: 4,
    SETTINGS_NOT_SATISFIED: 5,
    INTERNAL_ERROR: -1
}
```

I can submit a PR if this looks sensible to you.

**Comment by timmywil** [comment]
Interesting. It works for me without it having to exist in JS land.

**Comment by timmywil** [comment]
```ts
// Works in typescript...
import Geolocation, { GeoErrorCode } from 'react-native-geolocation-service'

console.log(GeoErrorCode.TIMEOUT) // 3
```

**Comment by tsvetan-ganev** [comment]
@timmywil, maybe it's a `tsconfig.json` setting. Do you mind sharing your config file?

**Comment by timmywil** [comment]
Sure,

```js
{
  "exclude": ["node_modules"],
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "es6",
      "esnext.asynciterable"
    ],
    "jsx": "react",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "baseUrl": "./",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  }
}
```
