### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNFusedLocation.startObserving')

### ISSUE THREAD

**Issue by joshuakoh7** [Agontuk/react-native-geolocation-service#84]
```
    Geolocation.clearWatch(this.watchID);
    this.watchID = Geolocation.watchPosition(
      position => {
        console.log("New position!");
      },
      error => console.log(error),
      {
        enableHighAccuracy: true,
        timeout: 20000,
        distanceFilter: 0
      }
    );
```

**Comment by Agontuk** [comment]
Please provide more details like package version, RN version etc.

**Comment by markwillis82** [comment]
I also receive this with getcurrentPosition:

`
Geolocation.getCurrentPosition(
        (position) => {
            console.log(position);
        },
        (error) => {
            // See error code charts below.
            console.log(error.code, error.message);
        },
        { enableHighAccuracy: false, timeout: 15000, maximumAge: 10000 }
    );
`
These are the packages.

    "react-native": "0.60.4",
    "react-native-geolocation-service": "^3.0.0",

The error received is:
ReactNativeJS ▶︎ Possible Unhandled Promise Rejection (id: 0):
                             │ TypeError: null is not an object (evaluating 'RNFusedLocation.getCurrentPosition')
                             │ getCurrentPosition$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:181123:32

Happy to provide more information as i'm at a bit of a loss on this now.

**Comment by Agontuk** [comment]
@markwillis82 , can you look inside the `node_modules/react-native-geolocation-service` and upload the contents of `js/index.js` and `RNFusedLocationModule.java` inside android folder to pastebin or similar site ?

**Comment by Agontuk** [comment]
> > @markwillis82 , can you look inside the `node_modules/react-native-geolocation-service` and upload the contents of `js/index.js` and `RNFusedLocationModule.java` inside android folder to pastebin or similar site ?
> > Also make sure you added `new RNFusedLocationPackage()` in `MainApplication.java`
> 
> Do you need to do that on react-native version 0.60+?

No.

**Comment by Crazypancakexd** [comment]
It fixed for me after I did `react-native run-android`

**Comment by spyshower** [comment]
I am still getting this. Any update?

**Comment by torchsmith** [comment]
Any updates? I'm still getting this.

**Comment by netshedzo** [comment]
I had a similar issue all i had to do was  run **react-native link react-native-geolocation-service** and then added **new RNFusedLocationPackage() in MainApplication.java**

**Comment by Agontuk** [comment]
Try the manual setup if it does not work out of the box.

**Comment by Temirtator** [comment]
issue is not solved

**Comment by coolprinze** [comment]
Had similar issue and this saved me within 5mins `[stackoverflow soluntion](https://stackoverflow.com/questions/56908771/typeerror-undefined-is-not-an-object-evaluating-navigator-geolocation-request)`

**Comment by oakis** [comment]
@coolprinze As also stated in the readme.

**Comment by torchsmith** [comment]
The solution I went with, which ended up being the easiest, was to just not use this at all. It has it's pros and cons though.

**Comment by sjitprogrammer** [comment]
Check These lines added in your MainApplication.java

import com.agontuk.RNFusedLocation.RNFusedLocationPackage;

add new RNFusedLocationPackage() in

 @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                    new MainReactPackage(),
                    new MapsPackage(),
                    new RNFusedLocationPackage()
                    
            );
        }

It fixes my issue

**Comment by Temirtator** [comment]
> Had similar issue and this saved me within 5mins `[stackoverflow soluntion](https://stackoverflow.com/questions/56908771/typeerror-undefined-is-not-an-object-evaluating-navigator-geolocation-request)`

that solution solved my issue

**Comment by dwijonarko** [comment]
> "react-native": "0.61.5",
> "react-native-geolocation-service": "^4.0.0",
> "react-native-maps": "^0.26.1"
> 
> Check These lines added in your MainApplication.java
> 
> import com.agontuk.RNFusedLocation.RNFusedLocationPackage;
> 
> add new RNFusedLocationPackage() in
> 
> @override
> protected List getPackages() {
> return Arrays.asList(
> new MainReactPackage(),
> new MapsPackage(),
> new RNFusedLocationPackage()
> 
> ```
>         );
>     }
> ```
> 
> It fixes my issue

Not working for me, did we still link manually in RN 0.60 ?

**Comment by Temirtator** [comment]
No

**Comment by oakis** [comment]
> Not working for me, did we still link manually in RN 0.60 ?

This question has been answered a million times and is in the README.md

**Comment by Agontuk** [comment]
Closing this, as this is setup related issue.

**Comment by prajna-h** [comment]
The above mentioned solutions didn't work for me... Is there any other solutions?

**Comment by prajna-h** [comment]
> "react-native": "0.61.5",
> "react-native-geolocation-service": "^4.0.0",
> "react-native-maps": "^0.26.1"
> 
> Check These lines added in your MainApplication.java
> 
> import com.agontuk.RNFusedLocation.RNFusedLocationPackage;
> 
> add new RNFusedLocationPackage() in
> 
> @override
> protected List getPackages() {
> return Arrays.asList(
> new MainReactPackage(),
> new MapsPackage(),
> new RNFusedLocationPackage()
> 
> ```
>         );
>     }
> ```
> 
> It fixes my issue

This didn't work for me

**Comment by prajna-h** [comment]
> Had similar issue and this saved me within 5mins `[stackoverflow soluntion](https://stackoverflow.com/questions/56908771/typeerror-undefined-is-not-an-object-evaluating-navigator-geolocation-request)`

react-native-community/geolocation Didn't work for me, that's why I switched to react-native-geolocation-service and now this is also not working

**Comment by Tigerz69** [comment]
> > Had similar issue and this saved me within 5mins `[stackoverflow soluntion](https://stackoverflow.com/questions/56908771/typeerror-undefined-is-not-an-object-evaluating-navigator-geolocation-request)`
> 
> react-native-community/geolocation Didn't work for me, that's why I switched to react-native-geolocation-service and now this is also not working

Me too, I use react-native-geolocation-service and that's solution not work, I can't fix this issue

**Comment by matek075** [comment]
any progress in this issue?

**Comment by medayoubammar** [comment]
any progress ?
i get same issue while using expo

**Comment by sercaneryaz** [comment]
i got same issue. fixed with add this lines to android/build.gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
ext {
    playServicesVersion = "18.0.0"
    playServicesLocationVersion = "21.0.1"
}
```

**Comment by Mynameisjohndev** [comment]
worked for me

**Comment by AliJabbar034** [comment]
> i got same issue. fixed with add this lines to android/build.gradle
> 
> ```
> // Top-level build file where you can add configuration options common to all sub-projects/modules.
> ext {
>     playServicesVersion = "18.0.0"
>     playServicesLocationVersion = "21.0.1"
> }
> ```

worked

**Comment by taruni29** [comment]
ext {
    playServicesVersion = "18.0.0"
    playServicesLocationVersion = "21.0.1"
}
Thanks !!..it worked for me
