### ISSUE TITLE
React Native 0.60: Cannot read property 'setRNConfiguration' of undefined

### ISSUE THREAD

**Issue by canpoyrazoglu** [Agontuk/react-native-geolocation-service#85]
I had to upgrade to 0.60 RC2 today (for AndroidX support) and I've started getting `Geolocation` (from `import Geolocation from 'react-native-geolocation-service';`) being undefined. I think it's most probably due to `react-native-geolocation` being removed from the core package. I've also installed `react-native-geolocation` separately but nothing changed.

How can I get `react-native-geolocation-service` back to working (without downgrading back to 0.59)?

**Comment by canpoyrazoglu** [comment]
I've worked around this issue by forking it, as I've described in https://github.com/Agontuk/react-native-geolocation-service/issues/69#issuecomment-505459359.

Though it still needs to be fixed in official repo.

**Comment by tsvetan-ganev** [comment]
A temporary fix which does not require forking or changing the library code:

```js
// App.js (preferrably at the top of the file)
navigator['geolocation'] = require('@react-native-community/geolocation')
```

**Comment by canpoyrazoglu** [comment]
@tsvetan-ganev That is even better! Though, keeping it open since both your and my solutions are just workarounds.

**Comment by Agontuk** [comment]
New version is available which fixes this issue, so closing this.
