### ISSUE TITLE
How can I observe the events of turning the GPS on and off?

### ISSUE THREAD

**Issue by joselitofilho** [Agontuk/react-native-geolocation-service#86]
How can I observe the events of turning the GPS on and off?

**Comment by oakis** [comment]
Before trying to fetch the location you can check for permissions.

https://facebook.github.io/react-native/docs/permissionsandroid

Dunno how to do it for iOS.

**Comment by havinhthai** [comment]
You can try [react-native-gps-state](https://github.com/neuberoliveira/react-native-gps-state).
