### ISSUE TITLE
Google location services is ON but still shows dialogue

### ISSUE THREAD

**Issue by oakis** [Agontuk/react-native-geolocation-service#87]
I have both location for my app set to on, and google location services on. Still I get the dialogue for enabling google location services.
Running Android 8.0 on a Nexus5 emulated device.

On my own OnePlus3 device with Android 9 it works. With both gps allowed and high accuracy enabled. If I disable high accuracy I get promted in the app, press OK and it gets activated and then works.

Pressing OK does not work in Android 8 on the Nexus5 emulator.

**Comment by oakis** [comment]
So i narrowed it down. It works for Android 9 but not 8. Pressing "OK" in the dialogue does nothing, so the user has to activate high precision manually.

**Comment by Agontuk** [comment]
Is it only the emulator or does real device have this problem too ?

**Comment by gghnisan** [comment]
I have a similar problem. 
I click "NO THANKS" and it repeats endlessly. I can not turn off geolocation. No such issues with navigator.geolocation.getCurrentPosition()
![untitled](https://user-images.githubusercontent.com/49828972/60394867-454fb600-9b33-11e9-859d-883fda65b54b.gif)

**Comment by oakis** [comment]
So at least one user has issues on a real device. I might be able to test this when I get home, I think I have an old device that I can install Android 8 on.

**Comment by eisenheim94** [comment]
I also experiencing an issue with two dialogues. If geolocation is off - it is asking to enable it twice. I have no `requestPermission` in code, so it is triggered by your module or by native code.

@gghnisan can you give me URL of PIN-code module you're using?

**Comment by eisenheim94** [comment]
Figured out why it is asking to enable geolocation twice.
It is because I'm calling `Geolocation.getCurrentPosition` first and `Geolocation.watchPosition` after.
Moved `Geolocation.watchPosition` to success callback from `Geolocation.getCurrentPosition` and second alert gone.

Anyway, you need to do some check that you already asked user to enable geolocation service.

**Comment by gghnisan** [comment]
I no longer use this library. And using standard navigator.geolocation.getCurrentPosition ()

**Comment by Agontuk** [comment]
I can't reproduce the issue, can anyone tell me the exact steps to reproduce this ?

@eisenheim94 why do you need to use both `getCurrentPosition` and `watchPosition` at the same time ?

**Comment by jibraniqbal666** [comment]
I am also experiencing this issue, even though, I have already accepted previous one. 
On the next launch when i get the same dialog again. because i am calling getCurrentLocation

**Comment by Agontuk** [comment]
Can you give me an example project which can reproduce this issue ?

**Comment by oakis** [comment]
> Can you give me an example project which can reproduce this issue ?

https://github.com/oakis/minahallplatser/blob/master/src/actions/search.js

**Comment by Agontuk** [comment]
> > Can you give me an example project which can reproduce this issue ?
> 
> https://github.com/oakis/minahallplatser/blob/master/src/actions/search.js

Can you check if 3.0.0 solves this issue ? It seems you're still using 2.0.0.

**Comment by oakis** [comment]
@Agontuk Should I use 3.0.0 with RN 0.59?

**Comment by Agontuk** [comment]
Yes, it works with RN0.59 too.

**Comment by oakis** [comment]
Using 3.0.0 doesn't fix the issue. I still have to manually enable high accuracy on the Android 8 device.

**Comment by oakis** [comment]
Tried with 3.1.0 and it is still not working.

Try to get location and this shows up:
```
For a better experience, turn on device location,
which uses Google's location service.

                                 NO THANKS    OK
```
Press OK

```
code: 5
message: "Location settings are not satisfied."
```

**Comment by Michae1-bom** [comment]
Any update on this? In my case unless the user set Location to "High accuracy", calling getCurrentPosition() would trigger the permission dialog, and pressing OK does not change the Location settings at all, which basically creates a loop. This is with version 4.0.0 and RN 0.60.5

**Comment by Agontuk** [comment]
> Any update on this? In my case unless the user set Location to "High accuracy", calling getCurrentPosition() would trigger the "For a better experience" dialog, and if you press "No thanks" the next getCurrentPosition call will trigger it again, which basically creates a loop. This is with version 4.0.0 and RN 0.60.5

If you set `enableHighAccuracy: true`, it'll always show the dialog unless location mode is already set to "High Accuracy".

**Comment by Michae1-bom** [comment]
> > Any update on this? In my case unless the user set Location to "High accuracy", calling getCurrentPosition() would trigger the "For a better experience" dialog, and if you press "No thanks" the next getCurrentPosition call will trigger it again, which basically creates a loop. This is with version 4.0.0 and RN 0.60.5
> 
> If you set `enableHighAccuracy: true`, it'll always show the dialog unless location mode is already set to "High Accuracy".

The main issue here is clicking OK doesn't actually change the settings properly and the next location request will cause the dialog to pop up again causing an infinite loop...

**Comment by Agontuk** [comment]
This is probably a device specific or google play service issue. Check [https://stackoverflow.com/questions/55520315/requesting-high-precision-location-with-locationsettingsrequest-not-updating-loc](https://stackoverflow.com/questions/55520315/requesting-high-precision-location-with-locationsettingsrequest-not-updating-loc).

Are you testing with samsung device ? You should try updating the play-services-location library version to see if it solves the issue. I've never faced this in my device (Xiaomi Redmi Note 3), so can't debug the issue unfortunately. I'll check their documentation just in case.

**Comment by Agontuk** [comment]
> The main issue here is clicking OK doesn't actually change the settings properly and the next location request will cause the dialog to pop up again causing an infinite loop...

Can you go inside node_modules and open the file `RNFusedLocationModule.java`, find the method `onActivityResult` and add this line as the first line ?

```java
Log.i(TAG, "ResultCode: " + resultCode);
```

Now from terminal run `/path/to/your/adb logcat "RNFusedLocation:*" "*:S"`. Check what is printed when you press "No Thanks" and "OK".

**Comment by thanhluantl2304** [comment]
i also faced this problem! On Samsung Galaxy A7, any update on this?

**Comment by Agontuk** [comment]
Is this still happening ? If it does, please do the debugging as described in the comment above and let me know the result from logcat.

**Comment by cantomas** [comment]
> Is this still happening ? If it does, please do the debugging as described in the comment above and let me know the result from logcat.

i faced this problem on Xiaomi Redmi Note 6 Pro (Android 9)

10-30 19:03:39.582  3093  3093 I RNFusedLocation: ResultCode: 0 // when you press "No"
10-30 19:05:56.390  4261  4261 I RNFusedLocation: ResultCode: -1 // when you press "Yes"
