### ISSUE TITLE
Could not determine the dependencies of task ':react-native-geolocation-service:compileDebugAidl'.

### ISSUE THREAD

**Issue by fabio-als-freitas** [Agontuk/react-native-geolocation-service#89]
Trying to install with RN0.60, and getting this:

> FAILURE: Build failed with an exception.

> What went wrong:
> Could not determine the dependencies of task ':react-native-geolocation-service:compileDebugAidl'.

> Could not resolve all task dependencies for configuration ':react-native-geolocation-service:debugCompileClasspath'.
   > Could not resolve com.android.support:appcompat-v7:28.0.0.
     Required by:
         project :react-native-geolocation-service
      > Cannot find a version of 'androidx.appcompat:appcompat' that satisfies the version constraints:
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'com.android.support:appcompat-v7:28.0.0' because of the following reason: ENABLE_JETIFIER is enabled
           Constraint path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'com.facebook.react:react-native:0.60.0' --> 'androidx.appcompat:appcompat:1.0.2'

   > Could not resolve androidx.appcompat:appcompat:{strictly 1.0.0}.
     Required by:
         project :react-native-geolocation-service
      > Cannot find a version of 'androidx.appcompat:appcompat' that satisfies the version constraints:
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'com.android.support:appcompat-v7:28.0.0' because of the following reason: ENABLE_JETIFIER is enabled
           Constraint path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'com.facebook.react:react-native:0.60.0' --> 'androidx.appcompat:appcompat:1.0.2'

   > Could not resolve androidx.core:core:{strictly 1.0.0}.
     Required by:
         project :react-native-geolocation-service
      > Cannot find a version of 'androidx.core:core' that satisfies the version constraints:
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.core:core:1.0.1'
           Constraint path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.core:core:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.vectordrawable:vectordrawable:1.0.1' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'com.google.android.gms:play-services-location:11.0.0' --> 'com.google.android.gms:play-services-basement:11.0.0' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.legacy:legacy-support-core-utils:1.0.0' --> 'androidx.loader:loader:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'com.google.android.gms:play-services-location:11.0.0' --> 'com.google.android.gms:play-services-basement:11.0.0' --> 'androidx.legacy:legacy-support-v4:1.0.0' --> 'androidx.media:media:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.customview:customview:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.viewpager:viewpager:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.coordinatorlayout:coordinatorlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.drawerlayout:drawerlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.slidingpanelayout:slidingpanelayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.swiperefreshlayout:swiperefreshlayout:1.0.0' --> 'androidx.core:core:1.0.0'
           Dependency path 'Test:react-native-geolocation-service:unspecified' --> 'androidx.appcompat:appcompat:1.0.2' --> 'androidx.fragment:fragment:1.0.0' --> 'androidx.legacy:legacy-support-core-ui:1.0.0' --> 'androidx.asynclayoutinflater:asynclayoutinflater:1.0.0' --> 'androidx.core:core:1.0.0'

Has anyone gone through this?

**Comment by smaldd14** [comment]
I am getting this same issue too with RN 0.60.0. Seems like this is a new issue with RN 0.60.0. See (https://github.com/react-native-community/react-native-maps/issues/2947).

Any fix for this?

**Comment by Agontuk** [comment]
I'm also getting error in RN60, will try to fix this as soon as possible.

**Comment by smaldd14** [comment]
> 
> 
> I'm also getting error in RN60, will try to fix this as soon as possible.

Any luck, @Agontuk  ?

**Comment by Agontuk** [comment]
@smaldd14 , can you try the new branch [https://github.com/Agontuk/react-native-geolocation-service/tree/rn60-fix](https://github.com/Agontuk/react-native-geolocation-service/tree/rn60-fix) ?

**Comment by jothikannan** [comment]
@smaldd14 How to install this branch? I just tried `npm install react-native-geolocation-service` I am still getting an error like Could not resolve com.android.support:appcompat-v7:28.0.0.

**Comment by fabio-als-freitas** [comment]
> @smaldd14 How to install this branch? I just tried `npm install react-native-geolocation-service` I am still getting an error like Could not resolve com.android.support:appcompat-v7:28.0.0.

Use: `npm install username/repo#branchName --save`

In this case: `npm install Agontuk/react-native-geolocation-service#rn60-fix`

**Comment by developerantoniosousa** [comment]
I had the same problem and solved it like this

Open the file `node_modules/react-native-geolocation-service/android/build.gradle` in dependencies and update

> compileOnly "com.facebook.react:react-native:+"

 to 

> implementation "com.facebook.react:react-native:+"

**Comment by oakis** [comment]
> I had the same problem and solved it like this
> 
> Open the file `node_modules/react-native-geolocation-service/android/build.gradle` in dependencies and update
> 
> > compileOnly "com.facebook.react:react-native:+"
> 
> to
> 
> > implementation "com.facebook.react:react-native:+"

Instead you could use version 3.0.0 of this package which has this fix in place.

**Comment by developerantoniosousa** [comment]
> > I had the same problem and solved it like this
> > Open the file `node_modules/react-native-geolocation-service/android/build.gradle` in dependencies and update
> > > compileOnly "com.facebook.react:react-native:+"
> > 
> > 
> > to
> > > implementation "com.facebook.react:react-native:+"
> 
> Instead you could use version 3.0.0 of this package which has this fix in place.


Thanks for the information

**Comment by fabio-als-freitas** [comment]
Solved, really thanks!

**Comment by fabio-als-freitas** [comment]
Solved, really thanks!
