### ISSUE TITLE
Upgrade to AndroidX

### ISSUE THREAD

**Issue by jahskee** [Agontuk/react-native-geolocation-service#94]
This module is great but needs to upgrade to support AndroidX.

**Comment by Agontuk** [comment]
It's been added in 3.0.0, so closing this.

**Comment by yairopro** [comment]
https://github.com/Agontuk/react-native-geolocation-service/blob/564fc1c4ab1546def51dea09bf1bed1ac3ee91f6/android/src/main/java/com/agontuk/RNFusedLocation/LocationUtils.java#L10

Hi @Agontuk 
It's not fully supported it seems..

**Comment by yairopro** [comment]
@Agontuk have a look on my PR #132 please.
