### ISSUE TITLE
Location doesn't update when mobile phone screen is locked?

### ISSUE THREAD

**Issue by faizaanshah** [Agontuk/react-native-geolocation-service#99]
I have written an application to collect some some sensors data via bluetooth and append gps coordinate to that data every single second and store it on a database. 
Problem is when screen is locked every single sensors data is fetched via bluetooth ( meaning app is running in background) but gps locations are not updated accordingly. But when screen is on every thing works fine.

**Comment by Agontuk** [comment]
This library does not track the state of the application. You should use Headless JS for doing background work and call geolocation API there.

**Comment by lyseiha** [comment]
Could u do sample headless task?

**Comment by Agontuk** [comment]
The current example project has foreground service which solves this issue. Basically even if screen is locked, the system will know the app is in foreground as long as the foreground service is active.
